import { test } from "node:test";
import { strict as assert } from "node:assert";
import { normalizeKey, parseRelationKey, relationKey } from "../core/normalize.js";
import { SimplicialModel } from "../core/model.js";
import {
  buildIncidenceMatrix,
  crossLayerMap,
  edgeSizes,
  nodeDegrees,
  pairwiseCooccurrence,
} from "../core/incidence.js";

// ---------------------------------------------------------------------------
// HG-01 — namespaced relation keys
// ---------------------------------------------------------------------------

test("relationKey round-trips through parseRelationKey", () => {
  const key = relationKey("hyperedge", ["Levinas.md", "AI Agent.md", "refusal.md"]);
  const parsed = parseRelationKey(key);
  assert.ok(parsed);
  assert.equal(parsed!.kind, "hyperedge");
  assert.equal(parsed!.nodeKey, normalizeKey(["Levinas.md", "AI Agent.md", "refusal.md"]));
});

test("a simplex and a hyperedge over the same nodes produce distinct keys", () => {
  const nodes = ["a.md", "b.md", "c.md"];
  assert.notEqual(relationKey("simplex", nodes), relationKey("hyperedge", nodes));
  assert.notEqual(relationKey("hyperedge", nodes), normalizeKey(nodes));
});

test("parseRelationKey rejects bare simplex keys", () => {
  assert.equal(parseRelationKey(normalizeKey(["a.md", "b.md"])), null);
  assert.equal(parseRelationKey("x:a.md|b.md"), null);
});

// ---------------------------------------------------------------------------
// HG-02 — the hyperedge store cannot leak into the simplicial layer
// ---------------------------------------------------------------------------

test("adding a hyperedge leaves the simplicial layer untouched", () => {
  const model = new SimplicialModel();
  const before = model.simplices.size;
  const key = model.addHyperedge({ nodes: ["levinas.md", "ai-agent.md", "refusal.md"] });

  assert.equal(model.simplices.size, before);
  assert.equal(model.hyperedges.size, 1);
  assert.ok(model.getHyperedge(key));
  // No faces: none of the three pairs exists as a simplex.
  assert.equal(model.simplices.has(normalizeKey(["levinas.md", "ai-agent.md"])), false);
  assert.equal(model.simplices.has(normalizeKey(["levinas.md", "refusal.md"])), false);
  assert.equal(model.simplices.has(normalizeKey(["ai-agent.md", "refusal.md"])), false);
});

test("addSimplex refuses an object tagged as a hyperedge", () => {
  const model = new SimplicialModel();
  const key = model.addSimplex({ nodes: ["a.md", "b.md", "c.md"], kind: "hyperedge" } as never);

  assert.equal(key, "");
  assert.equal(model.simplices.size, 0);
});

test("hyperedges do not perturb Betti numbers", () => {
  const model = new SimplicialModel();
  model.addSimplex({ nodes: ["a.md", "b.md"], userDefined: true });
  model.addSimplex({ nodes: ["b.md", "c.md"], userDefined: true });
  model.addSimplex({ nodes: ["a.md", "c.md"], userDefined: true });
  const before = model.getCachedBetti();
  assert.ok(before.b1 > 0, "three edges with no filling triangle leaves an unfilled cycle");

  model.addHyperedge({ nodes: ["a.md", "b.md", "c.md"], label: "irreducible encounter" });
  const after = model.getCachedBetti();

  assert.deepEqual(
    { b0: after.b0, b1: after.b1, b2: after.b2 },
    { b0: before.b0, b1: before.b1, b2: before.b2 },
    "an encounter over the triad does not fill the hole — only a simplex does",
  );
});

test("removeNode drops every hyperedge the node participated in", () => {
  const model = new SimplicialModel();
  model.addHyperedge({ nodes: ["a.md", "b.md", "c.md"] });
  model.addHyperedge({ nodes: ["d.md", "e.md"] });

  model.removeNode("b.md");

  assert.equal(model.hyperedges.size, 1);
  assert.equal(model.getHyperedgesForNode("a.md").length, 0);
});

test("updateNodeId rewrites hyperedge membership and rekeys it", () => {
  const model = new SimplicialModel();
  model.addHyperedge({ nodes: ["old.md", "other.md"], label: "encounter" });

  model.updateNodeId("old.md", "new.md");

  assert.equal(model.hyperedges.has(relationKey("hyperedge", ["new.md", "other.md"])), true);
  assert.equal(model.hyperedges.has(relationKey("hyperedge", ["old.md", "other.md"])), false);
  assert.equal(model.getHyperedgesForNode("new.md")[0].label, "encounter");
});

test("replaceSourceRelations clears both layers for the path it owns", () => {
  const model = new SimplicialModel();
  model.replaceSourceRelations(
    "note.md",
    [{ nodes: ["a.md", "b.md"], userDefined: true }],
    [{ nodes: ["c.md", "d.md", "e.md"] }],
  );
  assert.equal(model.hyperedges.size, 1);

  model.replaceSourceRelations("note.md", [], []);

  assert.equal(model.hyperedges.size, 0);
  assert.equal(
    [...model.simplices.values()].filter((simplex) => simplex.sourcePath === "note.md" && !simplex.autoGenerated)
      .length,
    0,
  );
});

test("getAllRelations tags each layer with its kind", () => {
  const model = new SimplicialModel();
  model.addSimplex({ nodes: ["a.md", "b.md"], userDefined: true });
  model.addHyperedge({ nodes: ["a.md", "b.md"] });

  const relations = model.getAllRelations();
  const kinds = relations.map((entry) => entry.relation.kind).sort();

  assert.deepEqual(kinds, ["hyperedge", "simplex"]);
  assert.equal(new Set(relations.map((entry) => entry.key)).size, 2, "same nodes, two distinct keys");
});

// ---------------------------------------------------------------------------
// HG-03 — incidence matrix and cross-layer map
// ---------------------------------------------------------------------------

test("incidence matrix matches a brute-force reference", () => {
  const model = new SimplicialModel();
  model.addHyperedge({ nodes: ["a.md", "b.md", "c.md"] });
  model.addHyperedge({ nodes: ["c.md", "d.md"] });

  const incidence = buildIncidenceMatrix(model);

  incidence.nodes.forEach((nodeId, row) => {
    incidence.edges.forEach((edgeKey, column) => {
      const expected = model.getHyperedge(edgeKey)!.nodes.includes(nodeId) ? 1 : 0;
      assert.equal(incidence.matrix[row * incidence.edges.length + column], expected, `${nodeId} × ${edgeKey}`);
    });
  });

  assert.equal(nodeDegrees(incidence).get("c.md"), 2);
  assert.equal(nodeDegrees(incidence).get("a.md"), 1);
  assert.equal(edgeSizes(incidence).get(relationKey("hyperedge", ["a.md", "b.md", "c.md"])), 3);
});

test("pairwise co-occurrence counts shared encounters without asserting the pairs", () => {
  const model = new SimplicialModel();
  model.addHyperedge({ nodes: ["a.md", "b.md", "c.md"] });
  model.addHyperedge({ nodes: ["a.md", "b.md"] });

  const counts = pairwiseCooccurrence(model);

  assert.equal(counts.get(normalizeKey(["a.md", "b.md"])), 2);
  assert.equal(counts.get(normalizeKey(["a.md", "c.md"])), 1);
  assert.equal(model.simplices.size, 0, "co-occurrence is a measurement, not a mutation");
});

test("cross-layer map separates present from missing implied faces", () => {
  const model = new SimplicialModel();
  model.addSimplex({ nodes: ["a.md", "b.md"], userDefined: true });
  const key = model.addHyperedge({ nodes: ["a.md", "b.md", "c.md"] });

  const map = crossLayerMap(model);
  const entry = map.hyperedges.get(key)!;

  assert.equal(entry.unbounded, false);
  // Implied: {a,b}, {a,c}, {b,c}, {a,b,c} — 2^3 − 3 − 1 = 4.
  assert.equal(entry.impliedFaceCount, 4);
  assert.deepEqual(entry.presentFaces, [normalizeKey(["a.md", "b.md"])]);
  assert.equal(entry.missingFaces.length, 3);
  assert.deepEqual(map.simplexCoveredBy.get(normalizeKey(["a.md", "b.md"])), [key]);
});

test("cross-layer map refuses to enumerate an oversized encounter", () => {
  const model = new SimplicialModel();
  const nodes = Array.from({ length: 12 }, (_, index) => `n${index}.md`);
  const key = model.addHyperedge({ nodes });

  const entry = crossLayerMap(model).hyperedges.get(key)!;

  assert.equal(entry.unbounded, true);
  assert.equal(entry.missingFaces.length, 0);
  assert.equal(entry.impliedFaceCount, Number.POSITIVE_INFINITY);
});

test("cross-layer cache invalidates on relation mutation", () => {
  const model = new SimplicialModel();
  const key = model.addHyperedge({ nodes: ["a.md", "b.md", "c.md"] });
  assert.equal(crossLayerMap(model).hyperedges.get(key)!.presentFaces.length, 0);

  model.addSimplex({ nodes: ["a.md", "b.md"], userDefined: true });

  assert.equal(crossLayerMap(model).hyperedges.get(key)!.presentFaces.length, 1);
});
