/* global console */
import { hashLabel } from "./hash.js";
import { normalizeKey, normalizeNodes } from "./normalize.js";
import type { NodeID, Simplex, SimplicialComplex } from "./types.js";
import { MAX_FACE_GEN_DIM } from "./types.js";

export function dim(simplex: Simplex): number {
  return simplex.nodes.length - 1;
}

export function* combinations<T>(arr: T[], k: number): Generator<T[]> {
  if (k === 0) {
    yield [];
    return;
  }
  for (let i = 0; i <= arr.length - k; i++) {
    for (const rest of combinations(arr.slice(i + 1), k - 1)) {
      yield [arr[i], ...rest];
    }
  }
}

export function generateFaces(complex: SimplicialComplex, simplex: Simplex): void {
  const simplexDim = dim(simplex);
  if (simplexDim > MAX_FACE_GEN_DIM) {
    console.warn(`[Simplicial] Simplex dim=${simplexDim} exceeds cap. Faces not auto-generated.`);
    return;
  }
  if (simplexDim === MAX_FACE_GEN_DIM) {
    return;
  }

  const nodes = normalizeNodes(simplex.nodes);
  for (let size = 2; size < nodes.length; size++) {
    for (const subset of combinations(nodes, size)) {
      const key = normalizeKey(subset);
      if (complex.simplices.has(key)) continue;
      complex.simplices.set(key, {
        nodes: normalizeNodes(subset),
        autoGenerated: true,
        userDefined: false,
        parentKey: normalizeKey(simplex.nodes),
        colorKey: simplex.colorKey ?? hashLabel(simplex.label),
      });
    }
  }
}

export function getFacesLazy(simplex: Simplex, targetDim: number): NodeID[][] {
  return [...combinations(simplex.nodes, targetDim + 1)];
}
