/* global console -- Allow console for warning output in browser environment (ESLint browser globals) */
import { hashLabel } from "./hash.js";
import { normalizeKey, normalizeNodes } from "./normalize.js";
import type { NodeID, Simplex, SimplicialComplex } from "./types.js";
import { MAX_FACE_GEN_DIM } from "./types.js";

export function dim(simplex: Simplex): number {
  return simplex.nodes.length - 1;
}

export function* combinations<T>(arr: T[], k: number): Generator<T[]> {
  if (k === 0) {
    yield [];
    return;
  }
  for (let i = 0; i <= arr.length - k; i++) {
    for (const rest of combinations(arr.slice(i + 1), k - 1)) {
      yield [arr[i], ...rest];
    }
  }
}

/**
 * Exactly the faces `generateFaces` would materialize, without materializing them.
 * Promotion shows this list to the user before asserting any of it, so the two must
 * not drift — `generateFaces` is defined in terms of this.
 */
export function plannedFaces(complex: SimplicialComplex, simplex: Simplex): NodeID[][] {
  const simplexDim = dim(simplex);
  if (simplexDim >= MAX_FACE_GEN_DIM) return [];

  const nodes = normalizeNodes(simplex.nodes);
  const faces: NodeID[][] = [];
  for (let size = 2; size < nodes.length; size++) {
    for (const subset of combinations(nodes, size)) {
      if (complex.simplices.has(normalizeKey(subset))) continue;
      faces.push(normalizeNodes(subset));
    }
  }
  return faces;
}

export function generateFaces(complex: SimplicialComplex, simplex: Simplex): void {
  const simplexDim = dim(simplex);
  if (simplexDim > MAX_FACE_GEN_DIM) {
    console.warn(`[Simplicial] Simplex dim=${simplexDim} exceeds cap. Faces not auto-generated.`);
    return;
  }

  const parentKey = normalizeKey(simplex.nodes);
  const colorKey = simplex.colorKey ?? hashLabel(simplex.label);
  for (const subset of plannedFaces(complex, simplex)) {
    complex.simplices.set(normalizeKey(subset), {
      nodes: subset,
      autoGenerated: true,
      userDefined: false,
      parentKey,
      colorKey,
    });
  }
}

export function getFacesLazy(simplex: Simplex, targetDim: number): NodeID[][] {
  return [...combinations(simplex.nodes, targetDim + 1)];
}
