import type { SimplicialModel } from "./model.js";
import { normalizeKey } from "./normalize.js";
import type { NodeID, RenderFilterMetric, Simplex, SimplexKey } from "./types.js";

export interface FiltrationValue {
  simplexKey: SimplexKey;
  dimension: number;
  score: number;
  /** Increasing sublevel value. The UI's decreasing score sweep uses 1-score. */
  value: number;
  metric: RenderFilterMetric;
  direction: "increasing";
}

export interface SimplexAppearanceEvent {
  threshold: number;
  type: "simplex-appearance";
  nodes: NodeID[];
  simplexKey: SimplexKey;
  description: string;
}

export type FiltrationEvent = SimplexAppearanceEvent;

/**
 * Mathematical object: a real-valued increasing filtration f on a finite simplicial complex.
 * Result used: sublevel sets are complexes iff f(face)≤f(coface).
 * Preconditions: all scores are finite and lie in [0,1].
 * Consequence: every prefix in the declared tie order is downward closed.
 * Witness: validated values with metric and direction provenance.
 * Non-claim: simplex appearances are not persistence births or deaths.
 * Reference: Edelsbrunner and Harer, Computational Topology, Ch. VII.
 */
export function buildFiltration(model: SimplicialModel, metric: RenderFilterMetric): FiltrationValue[] {
  const values = [...model.simplices.entries()].map(([simplexKey, simplex]) => {
    const score = getSimplexScore(simplex, metric);
    if (!Number.isFinite(score) || score < 0 || score > 1) throw new Error(`Invalid ${metric} score for ${simplexKey}`);
    return {
      simplexKey,
      dimension: simplex.nodes.length - 1,
      score,
      value: 1 - score,
      metric,
      direction: "increasing" as const,
    };
  });
  const byKey = new Map(values.map((entry) => [entry.simplexKey, entry]));
  for (const entry of values) {
    const nodes = entry.simplexKey.split("|");
    if (nodes.length <= 2) continue;
    for (let omitted = 0; omitted < nodes.length; omitted++) {
      const faceKey = normalizeKey(nodes.filter((_, index) => index !== omitted));
      const face = byKey.get(faceKey);
      if (!face) throw new Error(`Filtration input is not downward closed: ${entry.simplexKey} lacks ${faceKey}`);
      if (face.value > entry.value)
        throw new Error(`Filtration face condition violated: ${faceKey} follows ${entry.simplexKey}`);
    }
  }
  return values.sort(
    (a, b) => a.value - b.value || a.dimension - b.dimension || a.simplexKey.localeCompare(b.simplexKey),
  );
}

/** UI-history markers only. Persistence events arrive in v0.5.0 from matrix reduction. */
export function computeFiltrationEvents(model: SimplicialModel, metric: RenderFilterMetric): FiltrationEvent[] {
  return buildFiltration(model, metric)
    .map((entry) => ({
      threshold: entry.score,
      type: "simplex-appearance" as const,
      nodes: model.simplices.get(entry.simplexKey)?.nodes ?? entry.simplexKey.split("|"),
      simplexKey: entry.simplexKey,
      description: `${entry.dimension}-simplex appears: ${entry.simplexKey.split("|").join(" · ")}`,
    }))
    .sort(
      (a, b) =>
        b.threshold - a.threshold || a.nodes.length - b.nodes.length || a.simplexKey.localeCompare(b.simplexKey),
    );
}

function getSimplexScore(simplex: Simplex, metric: RenderFilterMetric): number {
  const fallback = simplex.autoGenerated ? 1 : 0;
  if (metric === "confidence") return simplex.confidence ?? simplex.weight ?? fallback;
  if (metric === "decayed-weight") return simplex.decayedWeight ?? simplex.weight ?? simplex.confidence ?? fallback;
  return simplex.weight ?? simplex.decayedWeight ?? simplex.confidence ?? fallback;
}

export function getEventThresholds(events: FiltrationEvent[]): number[] {
  const thresholds = new Set(events.map((event) => Math.round(event.threshold * 100) / 100));
  return [...thresholds].sort((a, b) => a - b);
}
