import { generateFaces } from "./faces.js";
import { hashLabel } from "./hash.js";
import { normalizeKey, normalizeNodes, uniqueNodes } from "./normalize.js";
import type { AnalysisSummary, LayoutNode, NodeID, Rect, Simplex, SimplexKey, BettiResult } from "./types.js";
import { computeBetti } from "./betti.js";

function randomInRange(min: number, max: number): number {
  return min + Math.random() * (max - min);
}

function randomBorderPosition(width: number, height: number, padding: number): { px: number; py: number } {
  const halfWidth = width / 2;
  const halfHeight = height / 2;
  const usableHalfWidth = Math.max(padding + 40, halfWidth - padding);
  const usableHalfHeight = Math.max(padding + 40, halfHeight - padding);
  const side = Math.floor(Math.random() * 4);

  switch (side) {
    case 0:
      return {
        px: randomInRange(-usableHalfWidth, usableHalfWidth),
        py: -usableHalfHeight,
      };
    case 1:
      return {
        px: usableHalfWidth,
        py: randomInRange(-usableHalfHeight, usableHalfHeight),
      };
    case 2:
      return {
        px: randomInRange(-usableHalfWidth, usableHalfWidth),
        py: usableHalfHeight,
      };
    default:
      return {
        px: -usableHalfWidth,
        py: randomInRange(-usableHalfHeight, usableHalfHeight),
      };
  }
}

function createNode(id: NodeID, bounds?: Rect, isVirtual = false): LayoutNode {
  const width = bounds?.width ?? 960;
  const height = bounds?.height ?? 640;
  const { px, py } = randomBorderPosition(width, height, 80);
  return {
    id,
    px,
    py,
    vx: 0,
    vy: 0,
    isVirtual,
    isPinned: false,
    displayAlpha: 1,
  };
}

type Listener = () => void;

export class SimplicialModel {
  readonly nodes = new Map<NodeID, LayoutNode>();
  readonly simplices = new Map<SimplexKey, Simplex>();
  private listeners = new Set<Listener>();
  private batchDepth = 0;
  private hasPendingEmit = false;

  // Analysis cache - invalidated on model mutation
  private _analysisCache: AnalysisSummary | null = null;
  private _analysisDirty = true;

  // Reverse index NodeID -> keys of simplices containing that node.
  // Derived cache, rebuilt lazily when dirty; invalidated alongside the analysis cache.
  private _nodeSimplexIndex: Map<NodeID, Set<SimplexKey>> | null = null;

  subscribe(listener: Listener): () => void {
    this.listeners.add(listener);
    return () => this.listeners.delete(listener);
  }

  private emitChange(): void {
    if (this.batchDepth > 0) {
      this.hasPendingEmit = true;
      return;
    }
    this.flushChange();
  }

  private flushChange(): void {
    this.listeners.forEach((listener) => listener());
  }

  batch<T>(fn: () => T): T {
    this.batchDepth++;
    try {
      return fn();
    } finally {
      this.batchDepth--;
      if (this.batchDepth === 0 && this.hasPendingEmit) {
        this.hasPendingEmit = false;
        this.flushChange();
      }
    }
  }

  setNode(id: NodeID, opts?: Partial<Pick<LayoutNode, "isVirtual" | "isPinned" | "px" | "py">>): void {
    const existing = this.nodes.get(id);
    if (existing) {
      Object.assign(existing, opts ?? {});
      if (opts?.isVirtual === false) existing.isVirtual = false;
      this.emitChange();
      return;
    }
    const node = createNode(id, undefined, opts?.isVirtual ?? false);
    if (opts?.px !== undefined) node.px = opts.px;
    if (opts?.py !== undefined) node.py = opts.py;
    if (opts?.isPinned !== undefined) node.isPinned = opts.isPinned;
    this.nodes.set(id, node);
    this.invalidateCaches();
    this.emitChange();
  }

  removeNode(id: NodeID): void {
    this.nodes.delete(id);
    for (const [key, simplex] of [...this.simplices]) {
      if (!simplex.nodes.includes(id)) continue;
      this.simplices.delete(key);
    }
    this.invalidateCaches();
    this.emitChange();
  }

  updateNodeId(oldId: NodeID, newId: NodeID): void {
    if (oldId === newId) return;
    const existing = this.nodes.get(oldId);
    if (existing) {
      this.nodes.set(newId, { ...existing, id: newId });
      this.nodes.delete(oldId);
    }

    for (const [key, simplex] of [...this.simplices]) {
      if (!simplex.nodes.includes(oldId)) continue;
      const updated = {
        ...simplex,
        nodes: normalizeNodes(simplex.nodes.map((node) => (node === oldId ? newId : node))),
      };
      this.simplices.delete(key);
      this.simplices.set(normalizeKey(updated.nodes), updated);
    }
    this.invalidateCaches();
    this.emitChange();
  }

  addSimplex(simplex: Simplex): string {
    const nodes = uniqueNodes(simplex.nodes);
    if (nodes.length < 2) return "";

    nodes.forEach((id) => {
      if (!this.nodes.has(id)) this.setNode(id, { isVirtual: false });
    });
    const normalized: Simplex = {
      ...simplex,
      nodes: normalizeNodes(nodes),
      weight: clampWeight(simplex.weight),
      autoGenerated: simplex.autoGenerated ?? false,
      userDefined: simplex.userDefined ?? !simplex.autoGenerated,
      colorKey: simplex.autoGenerated
        ? (simplex.colorKey ?? "neutral")
        : (simplex.colorKey ?? hashLabel(simplex.label)),
    };
    const key = normalizeKey(normalized.nodes);
    this.simplices.set(key, normalized);
    generateFaces(this, normalized);
    this.invalidateCaches();
    this.emitChange();
    return key;
  }

  removeSimplex(key: string): void {
    const removed = this.simplices.get(key);
    if (!this.simplices.delete(key)) return;
    // Rebuild the reverse index without the removed simplex before scanning for orphans.
    this._nodeSimplexIndex = null;

    // Only auto-generated faces that shared a node with the removed simplex can
    // have been orphaned by this removal, so restrict the scan to those candidates
    // (via the reverse index) instead of walking every simplex.
    const candidateKeys = new Set<SimplexKey>();
    for (const node of removed?.nodes ?? []) {
      for (const candidateKey of this.simplicesForNode(node)) {
        candidateKeys.add(candidateKey);
      }
    }
    for (const candidateKey of candidateKeys) {
      const simplex = this.simplices.get(candidateKey);
      if (!simplex?.autoGenerated) continue;
      const hasParent = simplex.nodes
        .map((node) => this.simplicesForNode(node))
        .reduce<Set<SimplexKey> | null>((acc, keys) => {
          const next = acc ? new Set([...acc].filter((k) => keys.has(k))) : new Set(keys);
          return next;
        }, null);
      const survives = [...(hasParent ?? [])].some((otherKey) => {
        if (otherKey === candidateKey) return false;
        return this.simplices.get(otherKey)?.autoGenerated === false;
      });
      if (!survives) this.simplices.delete(candidateKey);
    }
    this.invalidateCaches();
    this.emitChange();
  }

  replaceInferredSimplices(simplices: Simplex[]): void {
    this.batch(() => {
      for (const [key, simplex] of [...this.simplices]) {
        if (simplex.inferred) {
          this.simplices.delete(key);
        }
      }
      simplices.forEach((simplex) => {
        simplex.nodes.forEach((id) => {
          if (!this.nodes.has(id)) this.setNode(id, { isVirtual: false });
        });
        this.addSimplex(simplex);
      });
      this.invalidateCaches();
      this.emitChange();
    });
  }

  replaceSourceSimplices(sourcePath: string, simplices: Simplex[]): void {
    this.batch(() => {
      for (const [key, simplex] of [...this.simplices]) {
        if (simplex.sourcePath === sourcePath && !simplex.autoGenerated) {
          this.simplices.delete(key);
        }
      }
      simplices.forEach((simplex) => {
        simplex.nodes.forEach((id) => {
          if (!this.nodes.has(id)) this.setNode(id, { isVirtual: true });
        });
        this.addSimplex({ ...simplex, sourcePath });
      });
      this.invalidateCaches();
      this.emitChange();
    });
  }

  updateMetadata(key: string, meta: Partial<Pick<Simplex, "label" | "weight">>): void {
    const simplex = this.simplices.get(key);
    if (!simplex) return;
    const updated: Simplex = { ...simplex, ...meta };
    if (meta.label !== undefined) updated.colorKey = simplex.autoGenerated ? "neutral" : hashLabel(meta.label);
    if (meta.weight !== undefined) updated.weight = clampWeight(meta.weight);
    this.simplices.set(key, updated);
    this.invalidateCaches();
    this.emitChange();
  }

  setPinnedState(nodeId: NodeID, pinned: boolean, px?: number, py?: number): void {
    const node = this.nodes.get(nodeId);
    if (!node) return;
    node.isPinned = pinned;
    if (px !== undefined) node.px = px;
    if (py !== undefined) node.py = py;
    this.emitChange();
  }

  getSimplicesForNode(id: NodeID): Simplex[] {
    const out: Simplex[] = [];
    for (const key of this.simplicesForNode(id)) {
      const simplex = this.simplices.get(key);
      if (simplex) out.push(simplex);
    }
    return out;
  }

  /**
   * Keys of every simplex containing `id`, via the reverse index (O(1) lookup,
   * O(total membership) lazy rebuild). Includes auto-generated faces.
   */
  private simplicesForNode(id: NodeID): Set<SimplexKey> {
    return this.ensureNodeIndex().get(id) ?? new Set();
  }

  private ensureNodeIndex(): Map<NodeID, Set<SimplexKey>> {
    if (this._nodeSimplexIndex) return this._nodeSimplexIndex;
    const index = new Map<NodeID, Set<SimplexKey>>();
    for (const [key, simplex] of this.simplices) {
      for (const node of simplex.nodes) {
        let set = index.get(node);
        if (!set) {
          set = new Set();
          index.set(node, set);
        }
        set.add(key);
      }
    }
    this._nodeSimplexIndex = index;
    return index;
  }

  getNeighbors(id: NodeID): NodeID[] {
    const neighbors = new Set<NodeID>();
    this.getSimplicesForNode(id).forEach((simplex) => {
      simplex.nodes.forEach((node) => {
        if (node !== id) neighbors.add(node);
      });
    });
    return [...neighbors];
  }

  getSimplicesByDim(targetDim: number): Simplex[] {
    return [...this.simplices.values()].filter((simplex) => simplex.nodes.length - 1 === targetDim);
  }

  getAllNodes(): LayoutNode[] {
    return [...this.nodes.values()];
  }

  getSimplex(key: SimplexKey): Simplex | undefined {
    return this.simplices.get(key);
  }

  /**
   * Invalidate derived caches (analysis summary + reverse node index).
   * Called automatically on model mutations.
   */
  private invalidateCaches(): void {
    this._analysisDirty = true;
    this._nodeSimplexIndex = null;
  }

  /**
   * Get cached analysis summary. Recomputes only if cache is dirty.
   */
  getAnalysisSummary(): AnalysisSummary {
    if (!this._analysisDirty && this._analysisCache) {
      return this._analysisCache;
    }

    this._analysisCache = this.computeAnalysisSummary();
    this._analysisDirty = false;
    return this._analysisCache;
  }

  /**
   * Get cached Betti numbers. Reuses the analysis cache, computing the full
   * summary once if the cache is dirty rather than recomputing Betti standalone.
   */
  getCachedBetti(): BettiResult {
    return this.getAnalysisSummary().betti ?? { b0: 0, b1: 0, b2: 0, holes: [] };
  }

  private computeAnalysisSummary(): AnalysisSummary {
    const simplices = [...this.simplices.values()];
    const edgeSimplices = simplices.filter((simplex) => simplex.nodes.length === 2);
    const adjacency = new Map<NodeID, Set<NodeID>>();
    const simplexCentrality = new Map<NodeID, number>();
    this.nodes.forEach((_, nodeId) => adjacency.set(nodeId, new Set()));
    this.nodes.forEach((_, nodeId) => simplexCentrality.set(nodeId, 0));
    edgeSimplices.forEach((simplex) => {
      const [a, b] = simplex.nodes;
      adjacency.get(a)?.add(b);
      adjacency.get(b)?.add(a);
    });
    simplices.forEach((simplex) => {
      simplex.nodes.forEach((nodeId) => {
        simplexCentrality.set(nodeId, (simplexCentrality.get(nodeId) ?? 0) + 1);
      });
    });

    let connectedComponents = 0;
    const visited = new Set<NodeID>();
    adjacency.forEach((_, nodeId) => {
      if (visited.has(nodeId)) return;
      connectedComponents++;
      const stack = [nodeId];
      while (stack.length > 0) {
        const current = stack.pop()!;
        if (visited.has(current)) continue;
        visited.add(current);
        adjacency.get(current)?.forEach((neighbor) => {
          if (!visited.has(neighbor)) stack.push(neighbor);
        });
      }
    });

    let maxDegreeNodeId: NodeID | null = null;
    let maxDegree = -1;
    let degreeTotal = 0;
    adjacency.forEach((neighbors, nodeId) => {
      const degree = neighbors.size;
      degreeTotal += degree;
      if (degree > maxDegree) {
        maxDegree = degree;
        maxDegreeNodeId = nodeId;
      }
    });

    let maxSimplexCentralityNodeId: NodeID | null = null;
    let maxSimplexCentrality = -1;
    let simplexCentralityTotal = 0;
    simplexCentrality.forEach((centrality, nodeId) => {
      simplexCentralityTotal += centrality;
      if (centrality > maxSimplexCentrality) {
        maxSimplexCentrality = centrality;
        maxSimplexCentralityNodeId = nodeId;
      }
    });

    const betti = computeBetti(this, 2);
    const holeCount = betti.holes.length;

    return {
      nodeCount: this.nodes.size,
      simplexCount: simplices.length,
      edgeCount: edgeSimplices.length,
      clusterCount: simplices.filter((simplex) => simplex.nodes.length === 3).length,
      coreCount: simplices.filter((simplex) => simplex.nodes.length >= 4).length,
      inferredCount: simplices.filter((simplex) => simplex.inferred).length,
      suggestedCount: simplices.filter((simplex) => simplex.suggested).length,
      connectedComponents,
      averageDegree: this.nodes.size ? Number((degreeTotal / this.nodes.size).toFixed(2)) : 0,
      maxDegreeNodeId,
      maxDegree: Math.max(0, maxDegree),
      maxSimplexCentralityNodeId,
      maxSimplexCentrality: Math.max(0, maxSimplexCentrality),
      averageSimplexCentrality: this.nodes.size ? Number((simplexCentralityTotal / this.nodes.size).toFixed(2)) : 0,
      betti,
      holeCount,
    };
  }
}

function clampWeight(weight: number | undefined): number {
  if (weight === undefined || Number.isNaN(weight)) return 1;
  return Math.max(0.1, Math.min(1, weight));
}
