import { generateFaces } from "./faces";
import { hashLabel } from "./hash";
import { normalizeKey, normalizeNodes, uniqueNodes } from "./normalize";
import type { AnalysisSummary, LayoutNode, NodeID, Rect, Simplex, SimplexKey, BettiResult } from "./types";
import { computeBetti } from "./betti";

function randomInRange(min: number, max: number): number {
  return min + Math.random() * (max - min);
}

function randomBorderPosition(width: number, height: number, padding: number): { px: number; py: number } {
  const halfWidth = width / 2;
  const halfHeight = height / 2;
  const usableHalfWidth = Math.max(padding + 40, halfWidth - padding);
  const usableHalfHeight = Math.max(padding + 40, halfHeight - padding);
  const side = Math.floor(Math.random() * 4);

  switch (side) {
    case 0:
      return {
        px: randomInRange(-usableHalfWidth, usableHalfWidth),
        py: -usableHalfHeight,
      };
    case 1:
      return {
        px: usableHalfWidth,
        py: randomInRange(-usableHalfHeight, usableHalfHeight),
      };
    case 2:
      return {
        px: randomInRange(-usableHalfWidth, usableHalfWidth),
        py: usableHalfHeight,
      };
    default:
      return {
        px: -usableHalfWidth,
        py: randomInRange(-usableHalfHeight, usableHalfHeight),
      };
  }
}

function createNode(id: NodeID, bounds?: Rect, isVirtual = false): LayoutNode {
  const width = bounds?.width ?? 960;
  const height = bounds?.height ?? 640;
  const { px, py } = randomBorderPosition(width, height, 80);
  return {
    id,
    px,
    py,
    vx: 0,
    vy: 0,
    isVirtual,
    isPinned: false,
    displayAlpha: 1,
  };
}

type Listener = () => void;

export class SimplicialModel {
  readonly nodes = new Map<NodeID, LayoutNode>();
  readonly simplices = new Map<SimplexKey, Simplex>();
  private listeners = new Set<Listener>();
  private batchDepth = 0;
  private hasPendingEmit = false;

  // Analysis cache - invalidated on model mutation
  private _analysisCache: AnalysisSummary | null = null;
  private _analysisDirty = true;

  subscribe(listener: Listener): () => void {
    this.listeners.add(listener);
    return () => this.listeners.delete(listener);
  }

  private emitChange(): void {
    if (this.batchDepth > 0) {
      this.hasPendingEmit = true;
      return;
    }
    this.flushChange();
  }

  private flushChange(): void {
    this.listeners.forEach((listener) => listener());
  }

  batch<T>(fn: () => T): T {
    this.batchDepth++;
    try {
      return fn();
    } finally {
      this.batchDepth--;
      if (this.batchDepth === 0 && this.hasPendingEmit) {
        this.hasPendingEmit = false;
        this.flushChange();
      }
    }
  }

  setNode(id: NodeID, opts?: Partial<Pick<LayoutNode, "isVirtual" | "isPinned" | "px" | "py">>): void {
    const existing = this.nodes.get(id);
    if (existing) {
      Object.assign(existing, opts ?? {});
      if (opts?.isVirtual === false) existing.isVirtual = false;
      this.emitChange();
      return;
    }
    const node = createNode(id, undefined, opts?.isVirtual ?? false);
    if (opts?.px !== undefined) node.px = opts.px;
    if (opts?.py !== undefined) node.py = opts.py;
    if (opts?.isPinned !== undefined) node.isPinned = opts.isPinned;
    this.nodes.set(id, node);
    this.invalidateAnalysisCache();
    this.emitChange();
  }

  removeNode(id: NodeID): void {
    this.nodes.delete(id);
    for (const [key, simplex] of [...this.simplices]) {
      if (!simplex.nodes.includes(id)) continue;
      this.simplices.delete(key);
    }
    this.invalidateAnalysisCache();
    this.emitChange();
  }

  updateNodeId(oldId: NodeID, newId: NodeID): void {
    if (oldId === newId) return;
    const existing = this.nodes.get(oldId);
    if (existing) {
      this.nodes.set(newId, { ...existing, id: newId });
      this.nodes.delete(oldId);
    }

    for (const [key, simplex] of [...this.simplices]) {
      if (!simplex.nodes.includes(oldId)) continue;
      const updated = {
        ...simplex,
        nodes: normalizeNodes(simplex.nodes.map((node) => (node === oldId ? newId : node))),
      };
      this.simplices.delete(key);
      this.simplices.set(normalizeKey(updated.nodes), updated);
    }
    this.invalidateAnalysisCache();
    this.emitChange();
  }

  addSimplex(simplex: Simplex): string {
    const nodes = uniqueNodes(simplex.nodes);
    if (nodes.length < 2) return "";

    nodes.forEach((id) => {
      if (!this.nodes.has(id)) this.setNode(id, { isVirtual: false });
    });
    const normalized: Simplex = {
      ...simplex,
      nodes: normalizeNodes(nodes),
      weight: clampWeight(simplex.weight),
      autoGenerated: simplex.autoGenerated ?? false,
      userDefined: simplex.userDefined ?? !simplex.autoGenerated,
      colorKey: simplex.autoGenerated ? simplex.colorKey ?? "neutral" : simplex.colorKey ?? hashLabel(simplex.label),
    };
    const key = normalizeKey(normalized.nodes);
    this.simplices.set(key, normalized);
    generateFaces(this, normalized);
    this.invalidateAnalysisCache();
    this.emitChange();
    return key;
  }

  removeSimplex(key: string): void {
    if (!this.simplices.delete(key)) return;
    for (const [candidateKey, simplex] of [...this.simplices]) {
      if (!simplex.autoGenerated) continue;
      const hasParent = [...this.simplices.entries()].some(([otherKey, other]) => {
        if (otherKey === candidateKey) return false;
        if (other.autoGenerated) return false;
        return simplex.nodes.every((node) => other.nodes.includes(node));
      });
      if (!hasParent) this.simplices.delete(candidateKey);
    }
    this.invalidateAnalysisCache();
    this.emitChange();
  }

  replaceInferredSimplices(simplices: Simplex[]): void {
    this.batch(() => {
      for (const [key, simplex] of [...this.simplices]) {
        if (simplex.inferred) {
          this.simplices.delete(key);
        }
      }
      simplices.forEach((simplex) => {
        simplex.nodes.forEach((id) => {
          if (!this.nodes.has(id)) this.setNode(id, { isVirtual: false });
        });
        this.addSimplex(simplex);
      });
      this.invalidateAnalysisCache();
      this.emitChange();
    });
  }

  replaceSourceSimplices(sourcePath: string, simplices: Simplex[]): void {
    this.batch(() => {
      for (const [key, simplex] of [...this.simplices]) {
        if (simplex.sourcePath === sourcePath && !simplex.autoGenerated) {
          this.simplices.delete(key);
        }
      }
      simplices.forEach((simplex) => {
        simplex.nodes.forEach((id) => {
          if (!this.nodes.has(id)) this.setNode(id, { isVirtual: true });
        });
        this.addSimplex({ ...simplex, sourcePath });
      });
      this.invalidateAnalysisCache();
      this.emitChange();
    });
  }

  updateMetadata(key: string, meta: Partial<Pick<Simplex, "label" | "weight">>): void {
    const simplex = this.simplices.get(key);
    if (!simplex) return;
    const updated: Simplex = { ...simplex, ...meta };
    if (meta.label !== undefined) updated.colorKey = simplex.autoGenerated ? "neutral" : hashLabel(meta.label);
    if (meta.weight !== undefined) updated.weight = clampWeight(meta.weight);
    this.simplices.set(key, updated);
    this.invalidateAnalysisCache();
    this.emitChange();
  }

  setPinnedState(nodeId: NodeID, pinned: boolean, px?: number, py?: number): void {
    const node = this.nodes.get(nodeId);
    if (!node) return;
    node.isPinned = pinned;
    if (px !== undefined) node.px = px;
    if (py !== undefined) node.py = py;
    this.emitChange();
  }

  getSimplicesForNode(id: NodeID): Simplex[] {
    return [...this.simplices.values()].filter((simplex) => simplex.nodes.includes(id));
  }

  getNeighbors(id: NodeID): NodeID[] {
    const neighbors = new Set<NodeID>();
    this.getSimplicesForNode(id).forEach((simplex) => {
      simplex.nodes.forEach((node) => {
        if (node !== id) neighbors.add(node);
      });
    });
    return [...neighbors];
  }

  getSimplicesByDim(targetDim: number): Simplex[] {
    return [...this.simplices.values()].filter((simplex) => simplex.nodes.length - 1 === targetDim);
  }

  getAllNodes(): LayoutNode[] {
    return [...this.nodes.values()];
  }

  getSimplex(key: SimplexKey): Simplex | undefined {
    return this.simplices.get(key);
  }

  /**
   * Invalidate the analysis cache. Called automatically on model mutations.
   */
  private invalidateAnalysisCache(): void {
    this._analysisDirty = true;
  }

  /**
   * Get cached analysis summary. Recomputes only if cache is dirty.
   */
  getAnalysisSummary(): AnalysisSummary {
    if (!this._analysisDirty && this._analysisCache) {
      return this._analysisCache;
    }

    this._analysisCache = this.computeAnalysisSummary();
    this._analysisDirty = false;
    return this._analysisCache;
  }

  /**
   * Get cached Betti numbers. Recomputes only if cache is dirty.
   */
  getCachedBetti(): BettiResult {
    // Get from analysis cache if available, otherwise compute just Betti
    if (!this._analysisDirty && this._analysisCache) {
      return this._analysisCache.betti ?? { b0: 0, b1: 0, b2: 0, holes: [] };
    }
    return computeBetti(this, 2);
  }

  private computeAnalysisSummary(): AnalysisSummary {
    const simplices = [...this.simplices.values()];
    const edgeSimplices = simplices.filter((simplex) => simplex.nodes.length === 2);
    const adjacency = new Map<NodeID, Set<NodeID>>();
    const simplexCentrality = new Map<NodeID, number>();
    this.nodes.forEach((_, nodeId) => adjacency.set(nodeId, new Set()));
    this.nodes.forEach((_, nodeId) => simplexCentrality.set(nodeId, 0));
    edgeSimplices.forEach((simplex) => {
      const [a, b] = simplex.nodes;
      adjacency.get(a)?.add(b);
      adjacency.get(b)?.add(a);
    });
    simplices.forEach((simplex) => {
      simplex.nodes.forEach((nodeId) => {
        simplexCentrality.set(nodeId, (simplexCentrality.get(nodeId) ?? 0) + 1);
      });
    });

    let connectedComponents = 0;
    const visited = new Set<NodeID>();
    adjacency.forEach((_, nodeId) => {
      if (visited.has(nodeId)) return;
      connectedComponents++;
      const stack = [nodeId];
      while (stack.length > 0) {
        const current = stack.pop()!;
        if (visited.has(current)) continue;
        visited.add(current);
        adjacency.get(current)?.forEach((neighbor) => {
          if (!visited.has(neighbor)) stack.push(neighbor);
        });
      }
    });

    let maxDegreeNodeId: NodeID | null = null;
    let maxDegree = -1;
    let degreeTotal = 0;
    adjacency.forEach((neighbors, nodeId) => {
      const degree = neighbors.size;
      degreeTotal += degree;
      if (degree > maxDegree) {
        maxDegree = degree;
        maxDegreeNodeId = nodeId;
      }
    });

    let maxSimplexCentralityNodeId: NodeID | null = null;
    let maxSimplexCentrality = -1;
    let simplexCentralityTotal = 0;
    simplexCentrality.forEach((centrality, nodeId) => {
      simplexCentralityTotal += centrality;
      if (centrality > maxSimplexCentrality) {
        maxSimplexCentrality = centrality;
        maxSimplexCentralityNodeId = nodeId;
      }
    });

    const betti = computeBetti(this, 2);
    const holeCount = betti.holes.length;

    return {
      nodeCount: this.nodes.size,
      simplexCount: simplices.length,
      edgeCount: edgeSimplices.length,
      clusterCount: simplices.filter((simplex) => simplex.nodes.length === 3).length,
      coreCount: simplices.filter((simplex) => simplex.nodes.length >= 4).length,
      inferredCount: simplices.filter((simplex) => simplex.inferred).length,
      suggestedCount: simplices.filter((simplex) => simplex.suggested).length,
      connectedComponents,
      averageDegree: this.nodes.size ? Number((degreeTotal / this.nodes.size).toFixed(2)) : 0,
      maxDegreeNodeId,
      maxDegree: Math.max(0, maxDegree),
      maxSimplexCentralityNodeId,
      maxSimplexCentrality: Math.max(0, maxSimplexCentrality),
      averageSimplexCentrality: this.nodes.size ? Number((simplexCentralityTotal / this.nodes.size).toFixed(2)) : 0,
      betti,
      holeCount,
    };
  }
}

function clampWeight(weight: number | undefined): number {
  if (weight === undefined || Number.isNaN(weight)) return 1;
  return Math.max(0.1, Math.min(1, weight));
}
