export type NodeID = string;
export type SimplexKey = string;

export const VIEW_TYPE_SIMPLICIAL = "simplicial-view";
export const VIEW_TYPE_SIMPLICIAL_PANEL = "simplicial-panel";
export const VIEW_TYPE_SIMPLICIAL_SHEAF = "simplicial-sheaf";
export const VIEW_TYPE_SIMPLICIAL_DYNAMICS = "simplicial-dynamics";
export const MAX_FACE_GEN_DIM = 4;
export const MAX_RENDERED_DIM = 3;
export const HOLD_REPULSION = 900;

export const COLOR_PALETTE = ["purple", "teal", "coral", "pink", "blue", "amber"] as const;
export type ColorKey = (typeof COLOR_PALETTE)[number] | "neutral";
export type RenderFilterMetric = "weight" | "confidence" | "decayed-weight";
export type DomainSource = "folder" | "content-cluster" | "hybrid";
export type InferenceOutput = "simplex" | "hyperedge";

export interface BettiResult {
  b0: number;
  b1: number;
  b2: number;
  holes: Hole[];
}

export interface Hole {
  dimension: 1 | 2;
  boundaryNodes: NodeID[];
  missingSimplex: NodeID[];
}

export type SimplexSource = "user-defined" | "inferred-bridge" | "inferred-cross" | "inferred-nucleus" | "suggested";

export interface Simplex {
  nodes: NodeID[];
  weight?: number;
  label?: string;
  colorKey?: ColorKey;
  autoGenerated?: boolean;
  userDefined?: boolean;
  inferred?: boolean;
  source?: SimplexSource;
  sourcePath?: string;
  parentKey?: string;
  inferredSignals?: string[];
  dominantSignal?: string;
  confidence?: number;
  suggested?: boolean;
  decayedWeight?: number;
}

export interface SimplicialComplex {
  simplices: Map<SimplexKey, Simplex>;
}

/**
 * The two kinds of togetherness this plugin models.
 *
 * A simplex claims downward closure: asserting {A,B,C} asserts {A,B}, {A,C}, {B,C}.
 * A hyperedge claims nothing about its subgroups — it records an irreducible
 * encounter. Hyperedges must never pass through `generateFaces()`.
 */
export type RelationKind = "simplex" | "hyperedge";

/**
 * Namespaced relation key: `h:<node-hash>` for hyperedges.
 *
 * Asymmetry worth recording: simplex keys stay *bare* (`<node-hash>`, produced by
 * `normalizeKey`) so every pre-existing persisted reference, cache entry and focus
 * set keeps working. Hyperedges are namespaced from birth, which is what allows a
 * simplex and a hyperedge over the same node set to coexist — exactly the state
 * "promote to simplex" produces when it retains the encounter as provenance.
 */
export type RelationKey = string;

export type EncounterPersistence = "momentary" | "recurring";

/**
 * An irreducible group encounter. Makes no claim about its proper subgroups,
 * which is why it carries no `autoGenerated` notion and generates no faces.
 */
export interface Hyperedge {
  nodes: NodeID[];
  label?: string;
  colorKey?: ColorKey;
  weight?: number;
  /** First time this configuration was encountered. */
  occurredAt?: number;
  /** Timestamps of every recorded encounter, oldest first. Derived from the event log. */
  occurrences?: number[];
  persistence?: EncounterPersistence;
  sourcePath?: string;
  /** Free-form user vocabulary for the sort of encounter this was, e.g. "encounter". */
  mode?: string;
  /** Set when the user asserted the faces are meaningful; the encounter is retained as provenance. */
  promotedTo?: SimplexKey;
  /** Note produced by "crystallize concept", if any. */
  crystallizedInto?: NodeID;
  /** Probabilistic, in-memory candidate. It asserts no encounter and is never written until confirmed. */
  suggested?: boolean;
  /** Keeps independent suggestion passes from deleting one another's results. */
  suggestionSource?: "inference" | "encounter-discovery";
  inferred?: boolean;
  confidence?: number;
}

export type HigherOrderRelation = ({ kind: "simplex" } & Simplex) | ({ kind: "hyperedge" } & Hyperedge);

export interface LayoutNode {
  id: NodeID;
  px: number;
  py: number;
  vx: number;
  vy: number;
  isVirtual: boolean;
  isPinned: boolean;
  displayAlpha: number;
}

export interface Rect {
  width: number;
  height: number;
}

export interface PinnedState {
  [nodeId: string]: { px: number; py: number };
}

export interface PluginSettings {
  domainSource: DomainSource;
  contentClusterCount: number;
  enableBettiComputation: boolean;
  bettiDisplayOnCanvas: boolean;
  maxBettiDim: 1 | 2;
  showFiltrationSlider: boolean;
  enableExplanationPanel: boolean;
  enableInteractionReinforcement: boolean;
  reinforcementStrength: number;
  interactionState?: unknown;
  persistenceMode: "source-note" | "central-file";
  centralFile: string;
  showEdges: boolean;
  showClusters: boolean;
  showCores: boolean;
  maxRenderedDim: number;
  noiseAmount: number;
  sleepThreshold: number;
  repulsionStrength: number;
  cohesionStrength: number;
  gravityStrength: number;
  dampingFactor: number;
  boundaryPadding: number;
  darkMode: "auto" | "force-light" | "force-dark";
  inferenceMode: "emergent" | "taxonomic" | "hybrid";
  inferenceEmits: InferenceOutput;
  insightThreshold: number;
  linkStrengthThreshold: number;
  linkThresholdLowerBound: number;
  linkThresholdUpperBound: number;
  closureThreshold: number;
  tagRarityThreshold: number;
  decayHalfLifeDays: number;
  decayMinimumWeight: number;
  minDomainsForTriangle: number;
  minDomainsForTetra: number;
  minRolesForTetra: number;
  roleDiversityWeight: number;
  domainDiversityWeight: number;
  actionBonus: number;
  rareTagWeight: number;
  commonTagPenalty: number;
  linkGraphBaseline: boolean;
  enableInferredEdges: boolean;
  inferenceThreshold: number;
  enableLinkInference: boolean;
  enableMutualLinkBonus: boolean;
  enableSharedTags: boolean;
  enableTitleOverlap: boolean;
  enableContentOverlap: boolean;
  enableSameFolderInference: boolean;
  enableSameTopFolderInference: boolean;
  linkWeight: number;
  mutualLinkBonus: number;
  sharedTagWeight: number;
  titleOverlapWeight: number;
  contentOverlapWeight: number;
  sameFolderWeight: number;
  sameTopFolderWeight: number;
  showSuggestions: boolean;
  suggestionThreshold: number;
  commandSimplexSize: number;
  commandAutoOpenPanel: boolean;
  metadataHoverDelayMs: number;
  formalMode: boolean;
  sparseEdgeLength: number;
  sparseGravityBoost: number;
  labelDensity: number;
  renderFilterMetric: RenderFilterMetric;
  renderFilterThreshold: number;
  pinnedNodes: PinnedState;
  // --- hypergraph layer (v0.4.0) ---
  /** Defaults keep an existing vault visually identical until a hyperedge exists. */
  showHyperedges: boolean;
  hyperedgeOpacity: number;
  /**
   * Whether a focused encounter breathes its participants in phase. A kill switch
   * that stands alongside `prefers-reduced-motion`, not instead of it — the system
   * preference is honoured whatever this is set to.
   */
  enableHyperedgePulse: boolean;
  /** How many recorded encounters over the same node set flip it to "recurring". */
  encounterRecurrenceThreshold: number;
  /** Folder new notes from "crystallize concept" are created in; empty means vault root. */
  crystallizeFolder: string;
  /** Append-only relation event log (HG-30). */
  historyFile: string;
  enableRelationHistory: boolean;
  // --- dynamics (HG-19 … HG-21) ---
  /**
   * Registers the Dynamics Lab view and command. Off by default: it is an
   * experimental instrument, and a vault with no encounters has nothing to run.
   */
  enableDynamicsLab: boolean;
  /**
   * How fast ephemeral attention fades. Attention is never written to a note; this
   * only governs how long a note stays visibly in play after you leave it.
   */
  activationDecayHalfLifeMinutes: number;
  /** HG-25…HG-29. Validated by `data/sheaf-store`; never written into notes. */
  sheaf: unknown;
  enableEncounterSuggestions: boolean;
  encounterSuggestionThreshold: number;
  maxEncounterSuggestions: number;
  discoveryNoticeShown: boolean;
}

export interface RelationSelection {
  kind: RelationKind;
  key: RelationKey;
}

export interface FocusState {
  isActive: boolean;
  lockedNodeId: NodeID | null;
  hoveredNodeId: NodeID | null;
  hoveredSimplexKey: SimplexKey | null;
  hoveredHyperedgeKey: RelationKey | null;
  activeNodeIds: Set<NodeID>;
  activeSimplexKeys: Set<SimplexKey>;
  activeHyperedgeKeys: Set<RelationKey>;
  involvesNode(_nodeId: NodeID): boolean;
  involvesSimplex(_simplex: Simplex, _key?: SimplexKey): boolean;
  involvesRelation(_relation: HigherOrderRelation, _key?: RelationKey): boolean;
}

export interface ParserContext {
  sourcePath: string;
}

export interface SimplexRecord {
  key: SimplexKey;
  simplex: Simplex;
}

export interface ParsedFileResult {
  nodeIds: Set<NodeID>;
  simplices: Simplex[];
  hyperedges: Hyperedge[];
}

export interface MetadataSelection {
  key: SimplexKey | null;
}

export interface WritebackTarget {
  sourcePath: string;
  simplexKey: SimplexKey;
  kind: RelationKind;
}

export interface AnalysisSummary {
  nodeCount: number;
  simplexCount: number;
  hyperedgeCount: number;
  recurringEncounterCount: number;
  edgeCount: number;
  clusterCount: number;
  coreCount: number;
  inferredCount: number;
  suggestedCount: number;
  connectedComponents: number;
  averageDegree: number;
  maxDegreeNodeId: NodeID | null;
  maxDegree: number;
  maxSimplexCentralityNodeId: NodeID | null;
  maxSimplexCentrality: number;
  averageSimplexCentrality: number;
  betti?: BettiResult;
  holeCount: number;
}
