import type { SimplicialModel } from "../../core/model.js";
import { relationKey } from "../../core/normalize.js";
import type { Hyperedge, NodeID } from "../../core/types.js";
import type { SubsetScorer } from "../../core/diagnostics.js";

export interface EncounterSuggestionOptions {
  threshold: number;
  limit: number;
  score?: SubsetScorer;
}

/**
 * Fast structural proposal pass. It never asserts provenance or writes a note.
 * Maximal simplices provide coherent groups; junction triads sample notes that meet
 * through a shared hub but live in different maximal fields. Semantic evidence may
 * lift confidence, while a deterministic structural prior keeps startup bounded.
 */
export function suggestEncounters(model: SimplicialModel, options: EncounterSuggestionOptions): Hyperedge[] {
  const candidates = new Map<string, { nodes: NodeID[]; structural: number; reason: string }>();
  const maximal = [...model.simplices.values()].filter(
    (simplex) => !simplex.autoGenerated && simplex.nodes.length >= 3 && simplex.nodes.length <= 6,
  );
  const offer = (nodes: NodeID[], structural: number, reason: string) => {
    const key = relationKey("hyperedge", nodes);
    if (model.hyperedges.has(key)) return;
    const prior = candidates.get(key);
    if (!prior || structural > prior.structural) candidates.set(key, { nodes: [...nodes].sort(), structural, reason });
  };

  maximal.forEach((simplex) =>
    offer(simplex.nodes, 0.62 + 0.28 * (simplex.confidence ?? simplex.weight ?? 0.5), "coherent field"),
  );

  const memberships = new Map<NodeID, typeof maximal>();
  maximal.forEach((simplex) =>
    simplex.nodes.forEach((node) => memberships.set(node, [...(memberships.get(node) ?? []), simplex])),
  );
  memberships.forEach((groups, hub) => {
    for (let i = 0; i < groups.length; i++) {
      for (let j = i + 1; j < groups.length; j++) {
        const left = groups[i].nodes.find((node) => node !== hub && !groups[j].nodes.includes(node));
        const right = groups[j].nodes.find((node) => node !== hub && !groups[i].nodes.includes(node));
        if (left && right) offer([hub, left, right], 0.58, "cross-field junction");
      }
    }
  });

  return [...candidates.values()]
    .map(({ nodes, structural, reason }) => {
      const evidence = options.score?.(nodes) ?? structural;
      const confidence = Math.max(0, Math.min(1, structural * 0.7 + evidence * 0.3));
      return {
        nodes,
        label: `Possible encounter · ${reason}`,
        mode: "suggested",
        weight: confidence,
        confidence,
        suggested: true,
        inferred: true,
        suggestionSource: "encounter-discovery",
      } satisfies Hyperedge;
    })
    .filter((candidate) => (candidate.confidence ?? 0) >= options.threshold)
    .sort((a, b) => (b.confidence ?? 0) - (a.confidence ?? 0))
    .slice(0, Math.max(0, options.limit));
}
