import type { Simplex } from "../../core/types";
import type { InferenceConfig, InferenceContext, RawGraph, NoteProfile } from "./types";
import { buildRawGraph, getEdgeStrength, getNeighborsAbove } from "./graph";
import { detectOpenTriads } from "./rules/open-triad";
import { detectDensityClusters } from "./rules/density-cluster";
import { scoreCandidate } from "./scorer";
import type { CandidateSimplex } from "./types";

export function runEmergentInference(
  contexts: InferenceContext[],
  config: InferenceConfig,
): Simplex[] {
  console.time('runEmergentInference-buildGraph');
  const graph = buildRawGraph(contexts, config);
  console.timeEnd('runEmergentInference-buildGraph');

  console.time('runEmergentInference-detectTriads');
  const triads = detectOpenTriads(graph, config);
  console.timeEnd('runEmergentInference-detectTriads');

  console.time('runEmergentInference-detectClusters');
  const densityClusters = detectDensityClusters(graph, config);
  console.timeEnd('runEmergentInference-detectClusters');

  console.time('runEmergentInference-dedupe');
  const dedupedCandidates = new Map<string, CandidateSimplex>();

  [...triads, ...densityClusters].forEach((candidate) => {
    const key = [...candidate.nodes].sort().join("|");
    const current = dedupedCandidates.get(key);
    if (!current || (candidate.weight ?? 0) > (current.weight ?? 0)) {
      dedupedCandidates.set(key, candidate);
    }
  });
  const allCandidates = [...dedupedCandidates.values()];
  console.timeEnd('runEmergentInference-dedupe');

  console.time('runEmergentInference-score');
  const scored = allCandidates
    .map((c) => scoreCandidate(c, [...graph.nodes.values()], config))
    .filter((c) => c.insightScore >= config.insightThreshold && c.class !== 'folder-cluster')
    .sort((a, b) => b.insightScore - a.insightScore)
    .map((c) => ({
      nodes: c.nodes,
      weight: c.decayedWeight,
      label: c.label ?? undefined,
      source: c.source,
      sourcePath: undefined,
      autoGenerated: true,
      inferred: true,
      userDefined: false,
      suggested: true, // emergent inferences are always suggestions
      colorKey: 'neutral' as const,
      confidence: c.insightScore,
      decayedWeight: c.decayedWeight,
      inferredSignals: c.label === "density cluster" ? ["density-cluster"] : [],
      dominantSignal: c.label === "density cluster" ? 'semantic' : 'soft-cluster',
      // class is in type; we preserve via label where needed
    }));
  console.timeEnd('runEmergentInference-score');

  // Add graph edges as 1-simplices so basic links are visible
  // Fix 3: Percentile-based threshold (eliminates bistability cliff)
  console.time('runEmergentInference-edges');
  const edgeSimplices: Simplex[] = [];

  // Compute percentile-based threshold
  const allStrengths = [...graph.edges.values()]
    .map(e => e.strength)
    .filter(s => s > 0)
    .sort((a, b) => b - a);

  // slider = 0.0 → keep top edges (sparse); slider = 1.0 → keep all edges (dense)
  const keepFraction = 1 - config.linkStrengthThreshold;
  const cutoffIdx = Math.max(0, Math.floor(allStrengths.length * keepFraction) - 1);
  const effectiveThreshold = allStrengths[cutoffIdx] ?? 0;

  for (const edge of graph.edges.values()) {
    if (edge.strength >= effectiveThreshold) {
      edgeSimplices.push({
        nodes: [edge.a, edge.b],
        weight: edge.strength,
        source: 'suggested',
        sourcePath: undefined,
        autoGenerated: true,
        inferred: true,
        userDefined: false,
        suggested: edge.strength >= config.closureThreshold,
        colorKey: 'neutral',
        confidence: edge.strength,
        decayedWeight: edge.strength,
        inferredSignals: ['emergent-edge'],
        dominantSignal: 'link',
      });
    }
  }
  console.timeEnd('runEmergentInference-edges');

  return [...edgeSimplices, ...scored];
}

export function inferSimplicesEmergentWithMode(
  contexts: InferenceContext[],
  config: InferenceConfig,
): Simplex[] {
  return runEmergentInference(contexts, config);
}
