import type { Simplex, Hole } from "../../core/types.js";
import type { InferenceConfig, InferenceContext } from "./types.js";
import { buildRawGraph } from "./graph.js";
import { detectOpenTriads, detectOpenTriadsFromHoles } from "./rules/open-triad.js";
import { detectDensityClusters } from "./rules/density-cluster.js";
import { scoreCandidate } from "./scorer.js";
import type { CandidateSimplex } from "./types.js";

type RawGraph = ReturnType<typeof buildRawGraph>;

/**
 * Dedupe candidate simplices (keeping the strongest per node set), score them,
 * keep the insightful non-folder ones, and map to persisted Simplex records.
 */
function scoreCandidatesToSimplices(
  candidates: CandidateSimplex[],
  graph: RawGraph,
  config: InferenceConfig,
): Simplex[] {
  const dedupedCandidates = new Map<string, CandidateSimplex>();
  candidates.forEach((candidate) => {
    const key = [...candidate.nodes].sort().join("|");
    const current = dedupedCandidates.get(key);
    if (!current || (candidate.weight ?? 0) > (current.weight ?? 0)) {
      dedupedCandidates.set(key, candidate);
    }
  });

  const graphNodes = [...graph.nodes.values()];
  return [...dedupedCandidates.values()]
    .map((c) => scoreCandidate(c, graphNodes, config))
    .filter((c) => c.insightScore >= config.insightThreshold && c.class !== "folder-cluster")
    .sort((a, b) => b.insightScore - a.insightScore)
    .map((c) => ({
      nodes: c.nodes,
      weight: c.decayedWeight,
      label: c.label ?? undefined,
      source: c.source,
      sourcePath: undefined,
      autoGenerated: true,
      inferred: true,
      userDefined: false,
      suggested: true, // emergent inferences are always suggestions
      colorKey: "neutral" as const,
      confidence: c.insightScore,
      decayedWeight: c.decayedWeight,
      inferredSignals: c.label === "density cluster" ? ["density-cluster"] : [],
      dominantSignal: c.label === "density cluster" ? "semantic" : "soft-cluster",
    }));
}

/**
 * Emit raw graph edges as 1-simplices so basic links stay visible.
 * Uses a percentile-based cutoff (slider 0 → sparsest, 1 → all edges) to avoid a
 * bistability cliff around a fixed threshold.
 */
function buildEmergentEdgeSimplices(graph: RawGraph, config: InferenceConfig): Simplex[] {
  const allStrengths = [...graph.edges.values()]
    .map((e) => e.strength)
    .filter((s) => s > 0)
    .sort((a, b) => b - a);

  const keepFraction = 1 - config.linkStrengthThreshold;
  const cutoffIdx = Math.max(0, Math.floor(allStrengths.length * keepFraction) - 1);
  const effectiveThreshold = allStrengths[cutoffIdx] ?? 0;

  const edgeSimplices: Simplex[] = [];
  for (const edge of graph.edges.values()) {
    if (edge.strength >= effectiveThreshold) {
      edgeSimplices.push({
        nodes: [edge.a, edge.b],
        weight: edge.strength,
        source: "suggested",
        sourcePath: undefined,
        autoGenerated: true,
        inferred: true,
        userDefined: false,
        suggested: edge.strength >= config.closureThreshold,
        colorKey: "neutral",
        confidence: edge.strength,
        decayedWeight: edge.strength,
        inferredSignals: ["emergent-edge"],
        dominantSignal: "link",
      });
    }
  }
  return edgeSimplices;
}

export function runEmergentInference(contexts: InferenceContext[], config: InferenceConfig): Simplex[] {
  const graph = buildRawGraph(contexts, config);
  const triads = detectOpenTriads(graph, config);
  const densityClusters = detectDensityClusters(graph, config);

  const scored = scoreCandidatesToSimplices([...triads, ...densityClusters], graph, config);
  const edgeSimplices = buildEmergentEdgeSimplices(graph, config);
  return [...edgeSimplices, ...scored];
}

export function inferSimplicesEmergentWithMode(contexts: InferenceContext[], config: InferenceConfig): Simplex[] {
  return runEmergentInference(contexts, config);
}

/**
 * Run emergent inference using pre-computed Betti holes for triad detection.
 * This avoids the O(n × d²) enumeration by using already-computed β₁ holes.
 */
export function runEmergentInferenceWithHoles(
  contexts: InferenceContext[],
  config: InferenceConfig,
  holes: Hole[],
): Simplex[] {
  const graph = buildRawGraph(contexts, config);
  const triads = detectOpenTriadsFromHoles(holes, graph, config);
  const densityClusters = detectDensityClusters(graph, config);

  const scored = scoreCandidatesToSimplices([...triads, ...densityClusters], graph, config);
  const edgeSimplices = buildEmergentEdgeSimplices(graph, config);
  return [...edgeSimplices, ...scored];
}
