import type { Simplex, Hole } from "../../core/types";
import type { InferenceConfig, InferenceContext } from "./types";
import { buildRawGraph } from "./graph";
import { detectOpenTriads, detectOpenTriadsFromHoles } from "./rules/open-triad";
import { detectDensityClusters } from "./rules/density-cluster";
import { scoreCandidate } from "./scorer";
import type { CandidateSimplex } from "./types";

export function runEmergentInference(
  contexts: InferenceContext[],
  config: InferenceConfig,
): Simplex[] {
  const graph = buildRawGraph(contexts, config);
  const triads = detectOpenTriads(graph, config);
  const densityClusters = detectDensityClusters(graph, config);
  const dedupedCandidates = new Map<string, CandidateSimplex>();

  [...triads, ...densityClusters].forEach((candidate) => {
    const key = [...candidate.nodes].sort().join("|");
    const current = dedupedCandidates.get(key);
    if (!current || (candidate.weight ?? 0) > (current.weight ?? 0)) {
      dedupedCandidates.set(key, candidate);
    }
  });
  const allCandidates = [...dedupedCandidates.values()];

  const scored = allCandidates
    .map((c) => scoreCandidate(c, [...graph.nodes.values()], config))
    .filter((c) => c.insightScore >= config.insightThreshold && c.class !== 'folder-cluster')
    .sort((a, b) => b.insightScore - a.insightScore)
    .map((c) => ({
      nodes: c.nodes,
      weight: c.decayedWeight,
      label: c.label ?? undefined,
      source: c.source,
      sourcePath: undefined,
      autoGenerated: true,
      inferred: true,
      userDefined: false,
      suggested: true, // emergent inferences are always suggestions
      colorKey: 'neutral' as const,
      confidence: c.insightScore,
      decayedWeight: c.decayedWeight,
      inferredSignals: c.label === "density cluster" ? ["density-cluster"] : [],
      dominantSignal: c.label === "density cluster" ? 'semantic' : 'soft-cluster',
      // class is in type; we preserve via label where needed
    }));

  // Add graph edges as 1-simplices so basic links are visible
  // Fix 3: Percentile-based threshold (eliminates bistability cliff)
  const edgeSimplices: Simplex[] = [];

  // Compute percentile-based threshold
  const allStrengths = [...graph.edges.values()]
    .map(e => e.strength)
    .filter(s => s > 0)
    .sort((a, b) => b - a);

  // slider = 0.0 → keep top edges (sparse); slider = 1.0 → keep all edges (dense)
  const keepFraction = 1 - config.linkStrengthThreshold;
  const cutoffIdx = Math.max(0, Math.floor(allStrengths.length * keepFraction) - 1);
  const effectiveThreshold = allStrengths[cutoffIdx] ?? 0;

  for (const edge of graph.edges.values()) {
    if (edge.strength >= effectiveThreshold) {
      edgeSimplices.push({
        nodes: [edge.a, edge.b],
        weight: edge.strength,
        source: 'suggested',
        sourcePath: undefined,
        autoGenerated: true,
        inferred: true,
        userDefined: false,
        suggested: edge.strength >= config.closureThreshold,
        colorKey: 'neutral',
        confidence: edge.strength,
        decayedWeight: edge.strength,
        inferredSignals: ['emergent-edge'],
        dominantSignal: 'link',
      });
    }
  }

  return [...edgeSimplices, ...scored];
}

export function inferSimplicesEmergentWithMode(
  contexts: InferenceContext[],
  config: InferenceConfig,
): Simplex[] {
  return runEmergentInference(contexts, config);
}

/**
 * Run emergent inference using pre-computed Betti holes for triad detection.
 * This avoids the O(n × d²) enumeration by using already-computed β₁ holes.
 */
export function runEmergentInferenceWithHoles(
  contexts: InferenceContext[],
  config: InferenceConfig,
  holes: Hole[],
): Simplex[] {
  const graph = buildRawGraph(contexts, config);
  const triads = detectOpenTriadsFromHoles(holes, graph, config);
  const densityClusters = detectDensityClusters(graph, config);
  const dedupedCandidates = new Map<string, CandidateSimplex>();

  [...triads, ...densityClusters].forEach((candidate) => {
    const key = [...candidate.nodes].sort().join("|");
    const current = dedupedCandidates.get(key);
    if (!current || (candidate.weight ?? 0) > (current.weight ?? 0)) {
      dedupedCandidates.set(key, candidate);
    }
  });
  const allCandidates = [...dedupedCandidates.values()];

  const scored = allCandidates
    .map((c) => scoreCandidate(c, [...graph.nodes.values()], config))
    .filter((c) => c.insightScore >= config.insightThreshold && c.class !== 'folder-cluster')
    .sort((a, b) => b.insightScore - a.insightScore)
    .map((c) => ({
      nodes: c.nodes,
      weight: c.decayedWeight,
      label: c.label ?? undefined,
      source: c.source,
      sourcePath: undefined,
      autoGenerated: true,
      inferred: true,
      userDefined: false,
      suggested: true,
      colorKey: 'neutral' as const,
      confidence: c.insightScore,
      decayedWeight: c.decayedWeight,
      inferredSignals: c.label === "density cluster" ? ["density-cluster"] : [],
      dominantSignal: c.label === "density cluster" ? 'semantic' : 'soft-cluster',
    }));

  // Add graph edges as 1-simplices
  const edgeSimplices: Simplex[] = [];

  const allStrengths = [...graph.edges.values()]
    .map(e => e.strength)
    .filter(s => s > 0)
    .sort((a, b) => b - a);

  const keepFraction = 1 - config.linkStrengthThreshold;
  const cutoffIdx = Math.max(0, Math.floor(allStrengths.length * keepFraction) - 1);
  const effectiveThreshold = allStrengths[cutoffIdx] ?? 0;

  for (const edge of graph.edges.values()) {
    if (edge.strength >= effectiveThreshold) {
      edgeSimplices.push({
        nodes: [edge.a, edge.b],
        weight: edge.strength,
        source: 'suggested',
        sourcePath: undefined,
        autoGenerated: true,
        inferred: true,
        userDefined: false,
        suggested: edge.strength >= config.closureThreshold,
        colorKey: 'neutral',
        confidence: edge.strength,
        decayedWeight: edge.strength,
        inferredSignals: ['emergent-edge'],
        dominantSignal: 'link',
      });
    }
  }

  return [...edgeSimplices, ...scored];
}
