import type { SimplicialModel } from "../../core/model.js";
import { normalizeKey, normalizeNodeToken, relationKey } from "../../core/normalize.js";
import type { UncertaintyReport } from "../../core/topology/bootstrap.js";
import type {
  CycleRepresentative,
  PersistenceInterval,
  PersistenceResult,
} from "../../core/topology/persistence-types.js";
import type { NodeID, SimplexKey } from "../../core/types.js";
import type { DiscoveryExplanation } from "../discovery-explanation.js";

export interface PersistentGapOptions {
  /** Normalized lifetime a bar must clear before it is worth a writing prompt. */
  minimumNormalizedLifetime: number;
  /** Applied only when uncertainty was actually computed. */
  minimumBootstrapSupport: number;
  maximumWitnessSize: number;
  limit: number;
}

export const DEFAULT_GAP_OPTIONS: PersistentGapOptions = {
  minimumNormalizedLifetime: 0.15,
  minimumBootstrapSupport: 0.5,
  maximumWitnessSize: 8,
  limit: 10,
};

export interface PersistentGap {
  intervalId: string;
  /** Real vault node ids, resolved from the witness's normalized keys. */
  nodes: NodeID[];
  /** The verified witness itself, so a highlight draws the cycle rather than a reconstruction. */
  witnessKeys: SimplexKey[];
  explanation: DiscoveryExplanation;
}

/**
 * Rank persistent 1-dimensional gaps as writing prompts.
 *
 * Dimension 1 only in this release: a loop has a reading a writer can act on — these
 * notes circle something none of them states. A 2-dimensional void has no comparable
 * plain-language reading yet, and inventing one would be the failure mode this whole
 * release exists to correct.
 *
 * Every returned prompt carries its interval, representative, filtration provenance,
 * uncertainty and score breakdown. Nothing here asserts that a gap *should* be filled.
 */
export function rankPersistentGaps(
  model: SimplicialModel,
  result: PersistenceResult,
  options: PersistentGapOptions = DEFAULT_GAP_OPTIONS,
): PersistentGap[] {
  const representatives = new Map(result.representatives.map((entry) => [entry.intervalId, entry]));
  const support = new Map((result.uncertainty?.support ?? []).map((entry) => [entry.intervalId, entry]));
  const span = filtrationSpan(result.intervals);

  const gaps: PersistentGap[] = [];
  for (const interval of result.intervals) {
    if (interval.dimension !== 1) continue;

    const representative = representatives.get(interval.id);
    // A prompt without a verified witness cannot name the notes it is about.
    if (!representative) continue;

    const nodes = witnessNodes(model, representative);
    if (nodes.length === 0 || nodes.length > options.maximumWitnessSize) continue;

    // Already synthesized: a simplex spanning the whole cycle means the user has written
    // the connection, whatever the barcode says about the sub-relations.
    if (model.simplices.has(normalizeKey(nodes))) continue;

    const normalizedLifetime = normalizeLifetime(interval, span);
    if (normalizedLifetime < options.minimumNormalizedLifetime) continue;

    const bootstrapSupport = support.get(interval.id)?.supportFrequency ?? null;
    if (result.uncertainty && (bootstrapSupport ?? 0) < options.minimumBootstrapSupport) continue;

    gaps.push({
      intervalId: interval.id,
      nodes,
      witnessKeys: representative.simplices,
      explanation: explain(model, interval, representative, nodes, {
        normalizedLifetime,
        bootstrapSupport,
        uncertainty: result.uncertainty,
        metric: result.metric,
        tiePolicy: result.tiePolicy,
      }),
    });
  }

  return gaps
    .sort((a, b) => total(b.explanation) - total(a.explanation) || a.intervalId.localeCompare(b.intervalId))
    .slice(0, options.limit);
}

interface ExplainContext {
  normalizedLifetime: number;
  bootstrapSupport: number | null;
  uncertainty: UncertaintyReport | undefined;
  metric: string;
  tiePolicy: string;
}

function explain(
  model: SimplicialModel,
  interval: PersistenceInterval,
  representative: CycleRepresentative,
  nodes: NodeID[],
  context: ExplainContext,
): DiscoveryExplanation {
  const authored: string[] = [];
  const inferred: string[] = [];
  for (const key of representative.simplices) {
    const simplex = model.simplices.get(key);
    if (!simplex) continue;
    if (simplex.inferred || simplex.autoGenerated || simplex.suggested) inferred.push(key);
    else authored.push(key);
  }
  const inferredFraction = representative.simplices.length ? inferred.length / representative.simplices.length : 0;

  // Every node of the witness, not just the first: `nodes` is sorted, so scanning one
  // entry would silently miss an encounter over the rest of the cycle. Deduplicated by
  // relation key so an encounter spanning three witness notes is one piece of evidence.
  const recurrence = new Set(
    nodes.flatMap((node) =>
      model
        .getHyperedgesForNode(node)
        .filter((hyperedge) => hyperedge.persistence === "recurring")
        .map((hyperedge) => relationKey("hyperedge", hyperedge.nodes)),
    ),
  ).size;

  const scoreComponents: Record<string, number> = {
    normalizedLifetime: round(context.normalizedLifetime),
    bootstrapSupport: round(context.bootstrapSupport ?? 0),
    crossDomainDiversity: round(crossDomainDiversity(nodes)),
    representativeCompactness: round(compactness(nodes.length)),
    encounterRecurrence: round(Math.min(1, recurrence / 3) * 0.5),
    inferredEdgePenalty: round(-inferredFraction * 0.5),
    witnessComplexityPenalty: round(-Math.max(0, nodes.length - 4) * 0.05),
  };

  const uncertainty: string[] = [
    `Representative cycles are not canonical: another valid reduction of the same data yields a different witness for this class (tie policy ${context.tiePolicy}).`,
    `Birth and death are positions in the ${context.metric} filtration, not dates.`,
  ];
  if (context.uncertainty) {
    uncertainty.push(
      `${context.uncertainty.samplingScheme} ${Math.round((context.bootstrapSupport ?? 0) * 100)}% of ${context.uncertainty.completedSamples} completed resamples reproduced this feature.`,
    );
    if (context.uncertainty.truncated) {
      uncertainty.push(
        `The resampling budget stopped the run at ${context.uncertainty.completedSamples} of ${context.uncertainty.requestedSamples} samples, so support is measured on fewer samples than configured.`,
      );
    }
  } else {
    uncertainty.push("Empirical stability was not computed for this result, so no support frequency is claimed.");
  }
  if (inferredFraction > 0) {
    uncertainty.push(
      `${Math.round(inferredFraction * 100)}% of this cycle's relations were inferred by the plugin rather than asserted by you.`,
    );
  }

  return {
    claim: claimText(interval, nodes, context),
    kind: "persistent-gap",
    evidencePaths: nodes,
    contextIds: [],
    authoredInputs: authored,
    inferredInputs: inferred,
    scoreComponents,
    uncertainty,
    witnessRef: interval.id,
    suggestedAction: "write",
  };
}

function claimText(interval: PersistenceInterval, nodes: NodeID[], context: ExplainContext): string {
  const range =
    interval.death === null
      ? `from ${interval.birth.toFixed(2)} onward, never closing`
      : `across thresholds ${interval.birth.toFixed(2)}–${interval.death.toFixed(2)}`;
  const cycle = [...nodes, nodes[0]].map(shortName).join(" → ");
  const supportSentence =
    context.bootstrapSupport === null
      ? ""
      : ` It reappeared in ${Math.round(context.bootstrapSupport * 100)}% of configured subsamples.`;
  return `This loop persists ${range}. One representative connects ${cycle}.${supportSentence} Consider writing a synthesis that explains whether the loop should remain open or be filled.`;
}

/** Distinct top-level folders spanned by the witness, normalized. A loop inside one folder is less surprising. */
function crossDomainDiversity(nodes: NodeID[]): number {
  const domains = new Set(nodes.map((node) => (node.includes("/") ? node.slice(0, node.indexOf("/")) : "")));
  return nodes.length <= 1 ? 0 : Math.min(1, (domains.size - 1) / (nodes.length - 1));
}

/** A triangle-sized loop is actionable; a twenty-note loop is a description of the vault. */
function compactness(size: number): number {
  return size <= 3 ? 1 : Math.max(0, 1 - (size - 3) / 8);
}

function normalizeLifetime(interval: PersistenceInterval, span: number): number {
  // An essential class outlives every finite one, so it scores the maximum rather than
  // being dropped for having no death value.
  if (interval.lifetime === null) return 1;
  return span <= 0 ? 0 : Math.min(1, interval.lifetime / span);
}

function filtrationSpan(intervals: PersistenceInterval[]): number {
  const values = intervals.flatMap((interval) => [
    interval.birth,
    ...(interval.death === null ? [] : [interval.death]),
  ]);
  if (values.length === 0) return 0;
  return Math.max(...values) - Math.min(...values);
}

/**
 * Resolve a witness back to real notes.
 *
 * Simplex keys are normalized — lowercased tokens — so splitting one yields
 * "ideas/deep work.md", which is not a path anything can open and not a key
 * `getHyperedgesForNode` will match. The model holds the original ids; map back through
 * it, and fall back to the token only for a node the model no longer knows.
 */
function witnessNodes(model: SimplicialModel, representative: CycleRepresentative): NodeID[] {
  const byToken = new Map([...model.nodes.keys()].map((id) => [normalizeNodeToken(id), id]));
  const tokens = new Set<string>();
  for (const key of representative.simplices) key.split("|").forEach((token) => tokens.add(token));
  return [...tokens].map((token) => byToken.get(token) ?? token).sort();
}

function total(explanation: DiscoveryExplanation): number {
  return Object.values(explanation.scoreComponents).reduce((sum, value) => sum + value, 0);
}

function round(value: number): number {
  const rounded = Math.round(value * 1000) / 1000;
  // Negating a zero penalty yields -0, which the breakdown would print as "-0" and read
  // as a deduction that did not happen.
  return rounded === 0 ? 0 : rounded;
}

function shortName(node: NodeID): string {
  return node.replace(/\.md$/, "");
}
