import type { Simplex, Hole, NodeID } from "../core/types";
import type { InferenceContext, NoteProfile } from "./inference/types";

export interface SimplexExplanation {
  headline: string;
  tension: string;
  prompt: string;
  signals: string[];
}

/**
 * Generate a human-readable explanation of why a simplex was inferred
 * and what question it poses to the user.
 */
export function explainSimplex(
  simplex: Simplex,
  nodes: NoteProfile[],
  contexts: Map<string, InferenceContext>,
  holes: Hole[],
): SimplexExplanation {
  const nodeIds = simplex.nodes;
  const nodeProfiles = nodeIds.map(id => nodes.find(n => n.id === id)).filter(Boolean) as NoteProfile[];
  
  // Check if this simplex fills a hole
  const filledHole = holes.find(h => 
    h.missingSimplex.length === nodeIds.length &&
    h.missingSimplex.every(n => nodeIds.includes(n))
  );

  if (simplex.inferred) {
    return explainInferredSimplex(simplex, nodeProfiles, contexts, filledHole);
  }

  if (simplex.autoGenerated) {
    return explainAutoFace(simplex, nodeProfiles);
  }

  return explainUserDefinedSimplex(simplex, nodeProfiles);
}

function explainInferredSimplex(
  simplex: Simplex,
  nodes: NoteProfile[],
  contexts: Map<string, InferenceContext>,
  filledHole: Hole | undefined,
): SimplexExplanation {
  const dim = simplex.nodes.length - 1;
  const nodeNames = nodes.map(n => n.id.replace(/\.md$/, ""));
  const signals = simplex.inferredSignals ?? [];

  // Check for hole-filling
  if (filledHole) {
    return {
      headline: `This ${dim === 1 ? "edge" : dim === 2 ? "triangle" : "tetrahedron"} fills a topological hole in your complex.`,
      tension: `Notes ${nodeNames.join(" · ")} formed an unfilled cycle. This structure now binds them together.`,
      prompt: `Does this new connection reveal a synthesis you hadn't consciously noticed?`,
      signals: [`Fills β${filledHole.dimension} hole`, ...signals],
    };
  }

  // Bridge pattern detection
  if (dim === 2 && nodes.length === 3) {
    const bridgeNode = detectBridgeNode(nodes, contexts);
    if (bridgeNode) {
      const otherNodes = nodeNames.filter(n => n !== bridgeNode.replace(/\.md$/, ""));
      return {
        headline: "Three notes form a structural bridge through a common connection.",
        tension: `${otherNodes[0]} and ${otherNodes[1]} both connect to ${bridgeNode.replace(/\.md$/, "")}, but have no direct link between them.`,
        prompt: `What would a note directly relating "${otherNodes[0]}" and "${otherNodes[1]}" say?`,
        signals: ["Bridge pattern detected", ...signals],
      };
    }
  }

  // Cross-domain detection
  const domains = new Set(nodes.map(n => n.domain));
  if (domains.size > 1) {
    return {
      headline: `Cross-domain ${dim === 1 ? "relation" : dim === 2 ? "triangle" : "synthesis"} spanning ${domains.size} conceptual areas.`,
      tension: `Connects: ${[...domains].join(" · ")}. These domains rarely intersect in your vault.`,
      prompt: `What insight emerges from seeing these domains together?`,
      signals: [`Cross-domain: ${[...domains].join(" + ")}`, ...signals],
    };
  }

  // Default inferred explanation
  return {
    headline: `${dim === 1 ? "An inferred relation" : dim === 2 ? "An inferred triangle" : "An inferred higher-order structure"} among ${nodes.length} notes.`,
    tension: `Based on ${signals.length > 0 ? signals.join(" · ") : "vault structure analysis"}.`,
    prompt: `Is this a meaningful connection worth confirming?`,
    signals: signals.length > 0 ? signals : ["Pattern-based inference"],
  };
}

function explainAutoFace(
  simplex: Simplex,
  _nodes: NoteProfile[],
): SimplexExplanation {
  const dim = simplex.nodes.length - 1;

  return {
    headline: `Auto-generated face of a ${dim + 1}-simplex.`,
    tension: `This ${dim === 1 ? "edge" : dim === 2 ? "triangle" : "tetrahedron"} is the boundary of a higher-dimensional simplex you defined.`,
    prompt: `Faces help visualize the structure but cannot be edited independently.`,
    signals: [`Face of ${simplex.parentKey || "parent simplex"}`],
  };
}

function explainUserDefinedSimplex(
  simplex: Simplex,
  nodes: NoteProfile[],
): SimplexExplanation {
  const dim = simplex.nodes.length - 1;
  const nodeNamesList = nodes.map(n => n.id.replace(/\.md$/, ""));

  return {
    headline: `Confirmed ${dim === 1 ? "relation" : dim === 2 ? "triangle" : dim === 3 ? "tetrahedron" : "simplex"} you defined.`,
    tension: `You explicitly marked ${nodeNamesList.join(" · ")} as forming a meaningful structure.`,
    prompt: simplex.label 
      ? `Labeled as "${simplex.label}". Does this label still capture the relationship?`
      : `Consider adding a label to capture what binds these notes together.`,
    signals: simplex.label ? [`Label: ${simplex.label}`] : ["User-defined"],
  };
}

function detectBridgeNode(
  nodes: NoteProfile[],
  contexts: Map<string, InferenceContext>,
): NodeID | null {
  if (nodes.length !== 3) return null;

  for (const node of nodes) {
    const ctx = contexts.get(node.id);
    if (!ctx) continue;

    const otherNodes = nodes.filter(n => n.id !== node.id);
    const connectsToBoth = otherNodes.every(other => 
      ctx.outgoingLinks.has(other.id) || 
      contexts.get(other.id)?.outgoingLinks.has(node.id)
    );

    if (connectsToBoth) {
      // Check if the other two don't directly connect
      const [a, b] = otherNodes;
      const aCtx = contexts.get(a.id);
      const bCtx = contexts.get(b.id);
      const aLinksB = aCtx?.outgoingLinks.has(b.id) ?? false;
      const bLinksA = bCtx?.outgoingLinks.has(a.id) ?? false;
      
      if (!aLinksB && !bLinksA) {
        return node.id;
      }
    }
  }

  return null;
}

/**
 * Generate explanation for a hole (Betti void) rather than a simplex.
 */
export function explainHole(
  hole: Hole,
  contexts: Map<string, InferenceContext>,
): SimplexExplanation {
  const nodeNames = hole.boundaryNodes.map(id => id.replace(/\.md$/, ""));

  if (hole.dimension === 1) {
    return {
      headline: "A 1-dimensional hole in your complex — an unfilled triangle.",
      tension: `Notes ${nodeNames.join(" · ")} connect pairwise, but no synthesizing structure exists at the center.`,
      prompt: `What's at the center of this triangle? Writing a note that connects all three would close this hole.`,
      signals: ["β₁ hole: three notes, no triangle"],
    };
  }

  return {
    headline: "A 2-dimensional void — a hollow tetrahedron.",
    tension: `Four notes form a complete boundary of triangles, but the interior is empty.`,
    prompt: `What synthesis would fill this void? A note at the center would complete the structure.`,
    signals: ["β₂ void: four notes, no tetrahedron"],
  };
}
