import type { App } from "obsidian";
import { parseYaml } from "obsidian";
import { logger } from "../core/logger.js";
import { normalizeKey, normalizeNodes, resolveNodeId, uniqueNodes } from "../core/normalize.js";
import type { ParsedFileResult, Simplex } from "../core/types.js";

const SIMPLEX_MARKER = /^(\u25b3+|simplex:)\s+(.+)$/gim;

function canonicalizeNode(rawId: string, sourcePath: string, app: App): string {
  const resolved = resolveNodeId(rawId, sourcePath, app);
  return resolved?.path ?? rawId.trim();
}

function parseFrontmatterBlock(content: string): Record<string, unknown> | null {
  const match = content.match(/^---\n([\s\S]*?)\n---/);
  if (!match) return null;
  try {
    return (parseYaml(match[1]) as Record<string, unknown> | null) ?? null;
  } catch (error) {
    logger.warn("parser", "Failed to parse frontmatter", { error: error instanceof Error ? error.message : String(error) });
    return null;
  }
}

function simplexFromObject(input: unknown, sourcePath: string, app: App): Simplex | null {
  if (!input || typeof input !== "object") return null;
  const record = input as Record<string, unknown>;
  const rawNodes = Array.isArray(record.nodes) ? record.nodes.map(String) : [];
  const nodes = uniqueNodes(rawNodes.map((raw) => canonicalizeNode(raw, sourcePath, app)));
  if (nodes.length < 2) return null;
  return {
    nodes: normalizeNodes(nodes),
    label: typeof record.label === "string" ? record.label : undefined,
    weight: typeof record.weight === "number" ? record.weight : undefined,
    userDefined: true,
    autoGenerated: false,
    sourcePath,
  };
}

export function parseSimplices(content: string, sourcePath: string, app: App): ParsedFileResult {
  const frontmatter = parseFrontmatterBlock(content);
  const result: ParsedFileResult = { nodeIds: new Set(), simplices: [] };

  if (Array.isArray(frontmatter?.simplices)) {
    for (const entry of frontmatter.simplices) {
      const simplex = simplexFromObject(entry, sourcePath, app);
      if (!simplex) continue;
      simplex.nodes.forEach((nodeId) => result.nodeIds.add(nodeId));
      result.simplices.push(simplex);
    }
    logger.info("parser", "Parsed frontmatter simplices", {
      sourcePath,
      simplexCount: result.simplices.length,
      nodeCount: result.nodeIds.size
    });
    return dedupeParsed(result);
  }

  let match: RegExpExecArray | null;
  while ((match = SIMPLEX_MARKER.exec(content)) !== null) {
    const marker = match[1];
    const rawNodes = match[2].split(/\s+/).filter(Boolean);
    const expected = marker === "\u25b3\u25b3" ? 4 : marker === "\u25b3" ? 3 : rawNodes.length;
    const sliced = rawNodes.slice(0, expected);
    const nodes = uniqueNodes(sliced.map((raw) => canonicalizeNode(raw, sourcePath, app)));
    if (nodes.length < 2) continue;
    const simplex: Simplex = {
      nodes: normalizeNodes(nodes),
      sourcePath,
      userDefined: true,
      autoGenerated: false,
    };
    simplex.nodes.forEach((nodeId) => result.nodeIds.add(nodeId));
    result.simplices.push(simplex);
  }

  logger.info("parser", "Parsed inline simplices", {
    sourcePath,
    simplexCount: result.simplices.length,
    nodeCount: result.nodeIds.size
  });
  return dedupeParsed(result);
}

function dedupeParsed(result: ParsedFileResult): ParsedFileResult {
  const seen = new Set<string>();
  result.simplices = result.simplices.filter((simplex) => {
    const key = normalizeKey(simplex.nodes);
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
  return result;
}
