import { logger } from "../core/logger.js";
import { normalizeKey, normalizeNodes, uniqueNodes } from "../core/normalize.js";
import type { EncounterPersistence, Hyperedge, ParsedFileResult, Simplex } from "../core/types.js";

const SIMPLEX_MARKER = /^(△+|simplex:)\s+(.+)$/gim;
/**
 * Encounters have no fixed arity — the whole point is that the group is the unit —
 * so unlike `△`/`△△` this marker takes every token on the line.
 */
const HYPEREDGE_MARKER = /^(◇|hyperedge:|encounter:)\s+(.+)$/gim;

export interface ParserDeps {
  /** Resolve a raw token to a vault path, falling back to the trimmed token. */
  canonicalize(_rawId: string): string;
  /** YAML parse for the frontmatter block; returns null on malformed input. */
  parseYaml(_source: string): Record<string, unknown> | null;
}

function parseFrontmatterBlock(content: string, deps: ParserDeps): Record<string, unknown> | null {
  const match = content.match(/^---\n([\s\S]*?)\n---/);
  if (!match) return null;
  try {
    return deps.parseYaml(match[1]);
  } catch (error) {
    logger.warn("parser", "Failed to parse frontmatter", {
      error: error instanceof Error ? error.message : String(error),
    });
    return null;
  }
}

function readNodes(record: Record<string, unknown>, deps: ParserDeps): string[] {
  const rawNodes = Array.isArray(record.nodes) ? record.nodes.map(String) : [];
  return uniqueNodes(rawNodes.map((raw) => deps.canonicalize(raw)));
}

function simplexFromObject(input: unknown, sourcePath: string, deps: ParserDeps): Simplex | null {
  if (!input || typeof input !== "object") return null;
  const record = input as Record<string, unknown>;
  const nodes = readNodes(record, deps);
  if (nodes.length < 2) return null;
  return {
    nodes: normalizeNodes(nodes),
    label: typeof record.label === "string" ? record.label : undefined,
    weight: typeof record.weight === "number" ? record.weight : undefined,
    userDefined: true,
    autoGenerated: false,
    sourcePath,
  };
}

function hyperedgeFromObject(input: unknown, sourcePath: string, deps: ParserDeps): Hyperedge | null {
  if (!input || typeof input !== "object") return null;
  const record = input as Record<string, unknown>;
  const nodes = readNodes(record, deps);
  if (nodes.length < 2) return null;
  const persistence: EncounterPersistence = record.persistence === "recurring" ? "recurring" : "momentary";
  return {
    nodes: normalizeNodes(nodes),
    label: typeof record.label === "string" ? record.label : undefined,
    weight: typeof record.weight === "number" ? record.weight : undefined,
    mode: typeof record.mode === "string" ? record.mode : undefined,
    occurredAt: typeof record.occurredAt === "number" ? record.occurredAt : undefined,
    persistence,
    promotedTo: typeof record.promotedTo === "string" ? record.promotedTo : undefined,
    crystallizedInto: typeof record.crystallizedInto === "string" ? record.crystallizedInto : undefined,
    sourcePath,
  };
}

function parseInlineSimplices(content: string, sourcePath: string, deps: ParserDeps): Simplex[] {
  const simplices: Simplex[] = [];
  SIMPLEX_MARKER.lastIndex = 0;
  let match: RegExpExecArray | null;
  while ((match = SIMPLEX_MARKER.exec(content)) !== null) {
    const marker = match[1];
    const rawNodes = match[2].split(/\s+/).filter(Boolean);
    const expected = marker === "△△" ? 4 : marker === "△" ? 3 : rawNodes.length;
    const nodes = uniqueNodes(rawNodes.slice(0, expected).map((raw) => deps.canonicalize(raw)));
    if (nodes.length < 2) continue;
    simplices.push({
      nodes: normalizeNodes(nodes),
      sourcePath,
      userDefined: true,
      autoGenerated: false,
    });
  }
  return simplices;
}

function parseInlineHyperedges(content: string, sourcePath: string, deps: ParserDeps): Hyperedge[] {
  const hyperedges: Hyperedge[] = [];
  HYPEREDGE_MARKER.lastIndex = 0;
  let match: RegExpExecArray | null;
  while ((match = HYPEREDGE_MARKER.exec(content)) !== null) {
    const rawNodes = match[2].split(/\s+/).filter(Boolean);
    const nodes = uniqueNodes(rawNodes.map((raw) => deps.canonicalize(raw)));
    if (nodes.length < 2) continue;
    hyperedges.push({
      nodes: normalizeNodes(nodes),
      sourcePath,
      persistence: "momentary",
    });
  }
  return hyperedges;
}

/**
 * Parse both layers out of one note.
 *
 * Behaviour change in v0.4.0: this used to return early when `simplices:`
 * frontmatter was present, so inline `△` markers in a note that also carried
 * frontmatter simplices were silently dropped. Both sources are now merged, per
 * kind, with frontmatter entries winning on collision.
 */
export function parseRelations(content: string, sourcePath: string, deps: ParserDeps): ParsedFileResult {
  const frontmatter = parseFrontmatterBlock(content, deps);
  const result: ParsedFileResult = { nodeIds: new Set(), simplices: [], hyperedges: [] };

  if (Array.isArray(frontmatter?.simplices)) {
    for (const entry of frontmatter.simplices) {
      const simplex = simplexFromObject(entry, sourcePath, deps);
      if (simplex) result.simplices.push(simplex);
    }
  }
  if (Array.isArray(frontmatter?.hyperedges)) {
    for (const entry of frontmatter.hyperedges) {
      const hyperedge = hyperedgeFromObject(entry, sourcePath, deps);
      if (hyperedge) result.hyperedges.push(hyperedge);
    }
  }

  result.simplices.push(...parseInlineSimplices(content, sourcePath, deps));
  result.hyperedges.push(...parseInlineHyperedges(content, sourcePath, deps));

  const deduped = dedupeParsed(result);
  deduped.simplices.forEach((simplex) => simplex.nodes.forEach((nodeId) => deduped.nodeIds.add(nodeId)));
  deduped.hyperedges.forEach((hyperedge) => hyperedge.nodes.forEach((nodeId) => deduped.nodeIds.add(nodeId)));

  logger.info("parser", "Parsed relations", {
    sourcePath,
    simplexCount: deduped.simplices.length,
    hyperedgeCount: deduped.hyperedges.length,
    nodeCount: deduped.nodeIds.size,
  });
  return deduped;
}

/** Dedupe per kind — a simplex and a hyperedge over the same nodes are different claims. */
function dedupeParsed(result: ParsedFileResult): ParsedFileResult {
  const seenSimplices = new Set<string>();
  result.simplices = result.simplices.filter((simplex) => {
    const key = normalizeKey(simplex.nodes);
    if (seenSimplices.has(key)) return false;
    seenSimplices.add(key);
    return true;
  });

  const seenHyperedges = new Set<string>();
  result.hyperedges = result.hyperedges.filter((hyperedge) => {
    const key = normalizeKey(hyperedge.nodes);
    if (seenHyperedges.has(key)) return false;
    seenHyperedges.add(key);
    return true;
  });

  return result;
}
