import { ItemView, Notice, Setting, TFile, WorkspaceLeaf, type App } from "obsidian";
import { SimplicialModel } from "../core/model";
import type { PluginSettings, Simplex, SimplexKey } from "../core/types";
import { VIEW_TYPE_SIMPLICIAL_PANEL } from "../core/types";
import { effectiveColorForSimplex } from "../render/palette";
import { explainSimplex } from "../data/explainer";
import type { NoteProfile } from "../data/inference/types";

export class MetadataPanel extends ItemView {
  private simplexKey: SimplexKey | null = null;
  private saveMetadata?: (simplexKey: string, updates: { label?: string; weight?: number }) => Promise<void>;
  private promoteSimplex?: (simplexKey: string) => Promise<void>;
  private dissolveSimplex?: (simplexKey: string) => Promise<void>;
  private settings: PluginSettings | null = null;
  private nodeProfiles: NoteProfile[] = [];

  constructor(
    leaf: WorkspaceLeaf,
    private model: SimplicialModel,
  ) {
    super(leaf);
  }

  setSettings(settings: PluginSettings): void {
    this.settings = settings;
  }

  setNodeProfiles(profiles: NoteProfile[]): void {
    this.nodeProfiles = profiles;
  }

  getViewType(): string {
    return VIEW_TYPE_SIMPLICIAL_PANEL;
  }

  getDisplayText(): string {
    return "Simplicial metadata";
  }

  setActions(actions: {
    saveMetadata: (simplexKey: string, updates: { label?: string; weight?: number }) => Promise<void>;
    promoteSimplex: (simplexKey: string) => Promise<void>;
    dissolveSimplex: (simplexKey: string) => Promise<void>;
  }): void {
    this.saveMetadata = actions.saveMetadata;
    this.promoteSimplex = actions.promoteSimplex;
    this.dissolveSimplex = actions.dissolveSimplex;
  }

  setSelection(simplexKey: string | null): void {
    this.simplexKey = simplexKey;
    this.renderPanel();
  }

  async onOpen(): Promise<void> {
    this.renderPanel();
  }

  private renderPanel(): void {
    const { contentEl } = this;
    contentEl.empty();
    const simplex = this.simplexKey ? this.model.getSimplex(this.simplexKey) : null;
    contentEl.createEl("div", { cls: "simplicial-panel-title", text: "Simplex" });
    if (!simplex) {
      contentEl.createEl("div", { text: "Select a simplex or click a node cluster." });
      return;
    }

    // Render explanation card if enabled
    if (this.settings?.enableExplanationPanel) {
      this.renderExplanationCard(contentEl, simplex);
    }

    contentEl.createEl("div", { cls: "simplicial-panel-section-label", text: "Nodes" });
    contentEl.createEl("div", { cls: "simplicial-panel-value", text: simplex.nodes.join(" · ") });
    const analysis = this.model.getAnalysisSummary();
    const [r, g, b] = effectiveColorForSimplex(this.model, simplex);
    const badges = contentEl.createDiv({ cls: "simplicial-panel-badges" });
    this.renderBadge(badges, simplex.autoGenerated ? "Auto face" : simplex.inferred ? "Inferred" : "Confirmed", [r, g, b]);
    this.renderBadge(badges, `dim ${simplex.nodes.length - 1}`, [r, g, b]);
    if (simplex.sourcePath) this.renderBadge(badges, simplex.sourcePath.replace(/\.md$/, ""), [r, g, b], true);

    if (simplex.inferred) {
      contentEl.createEl("div", {
        cls: "simplicial-panel-value",
        text: `Inferred from: ${(simplex.inferredSignals ?? []).join(" · ") || "weighted vault signals"}`
      });
      contentEl.createEl("div", {
        cls: "simplicial-panel-value",
        text: `Confidence: ${Math.round((simplex.confidence ?? simplex.weight ?? 0) * 100)}%${simplex.suggested ? " · suggested" : ""}${simplex.decayedWeight !== undefined ? ` · decayed ${Math.round(simplex.decayedWeight * 100)}%` : ""}`
      });
    }

    const nodeCentralities = simplex.nodes.map((nodeId) => ({
      nodeId,
      centrality: this.model.getSimplicesForNode(nodeId).length,
    })).sort((a, b) => b.centrality - a.centrality);
    const centralityText = nodeCentralities
      .map(({ nodeId, centrality }) => `${nodeId.replace(/\.md$/, "")} (${centrality})`)
      .join(" · ");
    contentEl.createEl("div", {
      cls: "simplicial-panel-value",
      text: `Simplex centrality: ${centralityText || "n/a"}`
    });
    if (analysis.maxSimplexCentralityNodeId) {
      contentEl.createEl("div", {
        cls: "simplicial-panel-value",
        text: `Global hub: ${analysis.maxSimplexCentralityNodeId.replace(/\.md$/, "")} (${analysis.maxSimplexCentrality}) · avg ${analysis.averageSimplexCentrality}`
      });
    }

    if (!simplex.inferred) {
      contentEl.createEl("div", {
        cls: "simplicial-panel-value",
        text: `Persistence: ${simplex.sourcePath?.replace(/\.md$/, "") ?? "in memory"}`
      });
    }

    if (simplex.autoGenerated) {
      contentEl.createEl("div", {
        cls: "simplicial-panel-value",
        text: "Auto-generated face. Metadata editing is disabled."
      });
      contentEl.createEl("div", {
        cls: "simplicial-panel-footer",
        text: `dim: ${simplex.nodes.length - 1} · auto: yes`
      });
      return;
    }

    new Setting(contentEl)
      .setName("Label")
      .addText((text) => {
        text.setPlaceholder("unnamed");
        text.setValue(simplex.label ?? "");
        text.onChange((value) => {
          window.clearTimeout((text.inputEl as HTMLInputElement & { _simplicialTimer?: number })._simplicialTimer);
          (text.inputEl as HTMLInputElement & { _simplicialTimer?: number })._simplicialTimer = window.setTimeout(() => {
            void this.saveMetadata?.(this.simplexKey!, { label: value });
          }, 500);
        });
      });

    new Setting(contentEl)
      .setName("Weight")
      .setDesc(String(simplex.weight ?? 1))
      .addSlider((slider) => {
        let latestValue = simplex.weight ?? 1;
        slider.setLimits(0.1, 1, 0.1);
        slider.setValue(simplex.weight ?? 1);
        slider.onChange((value) => {
          latestValue = value;
          this.model.updateMetadata(this.simplexKey!, { weight: value });
          this.renderPanel();
        });
        slider.sliderEl.addEventListener("mouseup", () => {
          void this.saveMetadata?.(this.simplexKey!, { weight: latestValue });
        });
      });

    new Setting(contentEl)
      .addButton((button) => {
        button.setButtonText("Promote to note");
        button.onClick(async () => {
          if (!this.simplexKey) return;
          await this.promoteSimplex?.(this.simplexKey);
          new Notice("Simplex promoted to note.");
        });
      })
      .addExtraButton((button) => {
        button.setIcon("trash");
        button.setTooltip("Dissolve simplex");
        button.onClick(async () => {
          if (!this.simplexKey) return;
          await this.dissolveSimplex?.(this.simplexKey);
          new Notice("Simplex dissolved.");
        });
      });

    contentEl.createEl("div", {
      cls: "simplicial-panel-footer",
      text: `dim: ${simplex.nodes.length - 1} · auto: ${simplex.autoGenerated ? "yes" : "no"} · inferred: ${simplex.inferred ? "yes" : "no"}`,
    });
  }

  private renderExplanationCard(contentEl: HTMLElement, simplex: Simplex): void {
    const analysis = this.model.getAnalysisSummary();
    const holes = analysis.betti?.holes ?? [];

    const explanation = explainSimplex(simplex, this.nodeProfiles, new Map(), holes);

    const card = contentEl.createDiv({ cls: "simplicial-explanation-card" });

    // Headline
    card.createEl("div", {
      cls: "simplicial-explanation-headline",
      text: explanation.headline,
    });

    // Tension
    card.createEl("div", {
      cls: "simplicial-explanation-tension",
      text: explanation.tension,
    });

    // Prompt
    card.createEl("div", {
      cls: "simplicial-explanation-prompt",
      text: explanation.prompt,
    });

    // Signals (collapsible)
    if (explanation.signals.length > 0) {
      const signalsDiv = card.createDiv({ cls: "simplicial-explanation-signals" });
      signalsDiv.createEl("div", {
        cls: "simplicial-explanation-signals-label",
        text: "Evidence:",
      });
      explanation.signals.forEach(signal => {
        signalsDiv.createEl("div", {
          cls: "simplicial-explanation-signal",
          text: `• ${signal}`,
        });
      });
    }
  }

  private renderBadge(container: HTMLElement, text: string, color: [number, number, number], muted = false): void {
    container.createEl("span", {
      cls: "simplicial-panel-badge",
      text,
      attr: {
        style: muted
          ? `border-color: rgba(${color[0]},${color[1]},${color[2]},0.18); color: rgba(${color[0]},${color[1]},${color[2]},0.78);`
          : `background: rgba(${color[0]},${color[1]},${color[2]},0.12); border-color: rgba(${color[0]},${color[1]},${color[2]},0.28); color: rgb(${color[0]},${color[1]},${color[2]});`
      }
    });
  }
}

export async function createPromotedNote(app: App, fileName: string, content: string): Promise<TFile> {
  const stem = fileName.replace(/[\\/:*?"<>|]/g, "-").trim() || "simplex";
  let index = 0;
  while (true) {
    const path = `${stem}${index === 0 ? "" : `-${index}`}.md`;
    const existing = app.vault.getAbstractFileByPath(path);
    if (!(existing instanceof TFile)) {
      return app.vault.create(path, content);
    }
    index++;
  }
}
